### ISSUE TITLE
Nothing works after fresh install (.zshrc non-existant)

### ISSUE THREAD

**Issue by simonwjackson** [skwp/dotfiles#262]
I've followed the instructions for installing YADR in the README file:

``` bash
git clone https://github.com/skwp/dotfiles ~/.yadr
cd ~/.yadr && rake install
```

None of the commands in the README file seem to be working; including `prompt`, `yadr`, `ae`, `ar`, and so on... 

I looked in my home directory and a .zshrc file wasn't created. Could this be the problem?

**Comment by IrineuFilho** [comment]
@dpfranklin thanks. work for me
