### ISSUE TITLE
How not to vimify anything

### ISSUE THREAD

**Issue by dmitriy-kiriyenko** [skwp/dotfiles#263]
Hey,

I love these dotfiles expect vimification. I removed `editrc` and `inputrc`, removed `bindkey -v` but my main zsh prompt is still vimish. I want to totally remove this feature, using zsh itself with it's own native key bindings.

How do I achieve that?

**Comment by arunvelsriram** [comment]
@dmitriy-kiriyenko were you able to disable vimification ? Am struggling to find a way to do disable it.
