### ISSUE TITLE
zsh: bad math expression: operand expected at `%F{magenta...'

### ISSUE THREAD

**Issue by skwp** [skwp/dotfiles#272]
After prezto upgrade..skwp theme is a little broken. Git branch doesn't display and we get that error.

**Comment by benjaminmikiten** [comment]
I'm seeing this issue as well, specifically when I try to install [powerline](https://github.com/davidjrice/prezto_powerline).

**Comment by djadmin** [comment]
Thanks @TigerWolf. It works like charm.

**Comment by RoxanaTapia** [comment]
I think this might be the solution. edit your ~/.zpreztorc
 ':prezto:module:git:info' verbose 'yes'
