### ISSUE TITLE
Git autocomplete slow

### ISSUE THREAD

**Issue by skwp** [skwp/dotfiles#310]
This has been bothering me for a long time...

`gco [tab]...`

Why is branch autocomplete and even file autocomplete so slow? This is not yadr's issue per-se but maybe we can improve the zsh themes or git plugins that deal with this. If anyone has some ideas I'd love to hear them.

**Comment by gerrywastaken** [comment]
@sorin-ionescu I completely agree. I spent a lot of time trying to track down why intelligent autocomplete wasn't working on gia.
