### ISSUE TITLE
Warning message when opening a file in vim

### ISSUE THREAD

**Issue by nfarring** [skwp/dotfiles#35]
When opening a file in vim, a warning message appears. Vim opens after the warning message.

~yadr master ✔ ➤ which vim
vim: aliased to /usr/local/Cellar/macvim/7.3-64/MacVim.app/Contents/MacOS/Vim

~yadr master ✔ ➤ vim vimrc
'import site' failed; use -v for traceback
Error detected while processing /Users/nfarring/.yadr/vim/bundle/vim-scripts-AutoTag/plugin/autotag.vim:
line  166:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named os
Press ENTER or type command to continue

**Comment by nurulazradm** [comment]
thanks @junheon 

I did reinstall with `brew reinstall macvim`
