### ISSUE TITLE
Prezto theme not changing when installed with yadr

### ISSUE THREAD

**Issue by ravisuhag** [skwp/dotfiles#383]
i have configured sorin theme in .preztorc file but it is still loading last theme which is steeo-simplified  using prompt sorin changes theme but temp basis . How can i change theme permanently ...?

**Comment by rockymontana** [comment]
I got this problem too.
I've got it set in my .zpreztorc and as in the tip above, in ~/.zsh.after/prompt.zsh

**Comment by tarinidash** [comment]
open your terminal and try below

echo "prompt sorin" > ~/.zsh.after/prompt.zsh

**Comment by rkpasia** [comment]
If it can be useful to someone I've had this issue too but found the solution.

In the configuration file of zsh, .zshrc, there is the following code:
`for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file`

Inside the **folder ~/.yadr/zsh** there are all the files that configure zsh at the startup, so in the **theme.zsh** you can change your theme of choice: `prompt steeef`
