### ISSUE TITLE
Errors when using vim (inside and outside of tmux)

### ISSUE THREAD

**Issue by cdenneen** [skwp/dotfiles#398]
AddTabularPattern: Vim(let):E117: Unknown function: tabular#ElementFormatPattern
AddTabularPattern: Vim(let):E117: Unknown function: tabular#ElementFormatPattern
AddTabularPattern: Vim(let):E117: Unknown function: tabular#ElementFormatPattern
AddTabularPattern: Vim(let):E117: Unknown function: tabular#ElementFormatPattern
AddTabularPattern: Vim(let):E117: Unknown function: tabular#ElementFormatPattern
AddTabularPattern: Vim(let):E117: Unknown function: tabular#ElementFormatPattern

Error detected while processing FileType Auto commands for "_":
E117: Unknown function: TagHighlight#ReadTypes#ReadTypesByFileType
Error detected while processing BufRead Auto commands for "_":
E117: Unknown function: TagHighlight#ReadTypes#ReadTypesByExtension
Error detected while processing VimEnter Auto commands for "*":
E117: Unknown function: xolox#session#auto_load

**Comment by leodotcloud** [comment]
I just ran into the same issue. Luckily I had my old laptop handy to compare the filesystems. Realized, I had some stale files like `.gvimrc`, `.vimrc.after`, etc pointing to some old settings. Cleaning them up fixed this error.
