### ISSUE TITLE
fish-style autosuggest

### ISSUE THREAD

**Issue by alexbw** [skwp/dotfiles#433]
This is an interesting project, and is the only hold-over feature from fish that I was missing in zsh.

https://github.com/tarruda/zsh-autosuggestions

Would be cool to integrate it into this project, or have an option to flip it on.

**Comment by lfilho** [comment]
A friend just sent me this. It seems this is now officially part of `zsh-users`: https://github.com/zsh-users/zsh-autosuggestions . @skwp could you take a look to see if that weird behavior you mentioned above still occurs?

If not, I'm happy to swing a quick PR for this.

Cheers

**Comment by lfilho** [comment]
It seems this was a problem with zsh that got fixed somewhat recently: https://github.com/sorin-ionescu/prezto/issues/1245

**Comment by lfilho** [comment]
Hmm... Investigating a bit more, seems like this is now part of Prezto already: https://github.com/sorin-ionescu/prezto/tree/master/modules/autosuggestions

So it'd be only a matter of enabling such module...
