### ISSUE TITLE
How to complete uninstall?

### ISSUE THREAD

**Issue by fellipeh** [skwp/dotfiles#489]
How to complete uninstall? I try to remove .yadr folder, but zsh terminal broken

or disable zsh, and get the "default" terminal back?

**Comment by SalvaCarsi** [comment]
Hi Yan, you are doing a nice job with yard. However it will be nice to have the uninstall script.  
For now I have just run in the terminal the command <code>chsh -s /bin/bash</code>. Until the script is available. 
Cheers.

**Comment by ieo** [comment]
Thanks @skwp. Trying to learn vim, but it's been killing me trying to learn at the console.

**Comment by puncsky** [comment]
It would be really nice if we have a way to uninstall it... thanks a lot :)

**Comment by jaysoifer** [comment]
+1

**Comment by yunusemrecan** [comment]
+1

**Comment by alexguo** [comment]
i use this command to clean yadr
```
cd ~/
ll -la | grep yadr | awk '{print $9}' | xargs rm -rf
```

**Comment by christopherturner** [comment]
+1

**Comment by halink0803** [comment]
+2

**Comment by BirkhoffLee** [comment]
+1

**Comment by SvenKreussler** [comment]
+1

**Comment by cdavaz** [comment]
+1
