### ISSUE TITLE
Solarized .itermcolors not being "installed" properly

### ISSUE THREAD

**Issue by dsimmons** [skwp/dotfiles#518]
##### Steps to reproduce:
1. Fresh install of OSX latest on a new MBP.
2. Installed Homebrew and iTerm2.
3. Installed `zsh`, `tmux`, and `vim --with-lua` through Homebrew.
4. Cloned `yadr`, ran `install.sh`.

Everything else worked great, but neither `Solarized Dark.itermcolors` nor `Solarized Light.itermcolors` show up in the available selections. I had to manually perform the following:
- Choose `Import...`.
- Create a non-hidden alias (used a symlink) for `~/.yadr`, because it's a dotfile and doesn't show up in the list of selections.
- Select both of the files.

See the picture below for a screenshot. After performing the above, it worked great.

While it wasn't a ton of hoops to jump through, I'm mainly creating an issue because it was confusing -- both the installer prompts and the documentation make it sound like all you have to do is select "Solarized {Light,Dark}" from the list of available palettes (respectively), but they don't appear on the list.
##### A quick pass at debugging

I tried manually running the respective `PlistBuddy` lines that should perform the above in the `Rakefile`, but as far as I could tell, they didn't do anything:

``` Shell
$ /usr/libexec/PlistBuddy -c "Add :'Custom Color Presets':'Solarized Dark' dict" ~/Library/Preferences/com.googlecode.iterm2.plist
$ /usr/libexec/PlistBuddy -c "Merge 'iTerm2/Solarized Dark.itermcolors' :'Custom Color Presets':'Solarized Dark'" ~/Library/Preferences/com.googlecode.iterm2.plist
```
##### Screenshot

![screenshot](https://dl.dropboxusercontent.com/u/6968139/oss/issues/Screenshot%202014-08-07%2022.53.52.png)

**Comment by lfilho** [comment]
Hello everyone. Closing this issue as it's too old now. We've even had more OSX versions after the one mentioned in here, so I think this issue is irrelevant now. Feel free to reopen if needed. Cheers.
