### ISSUE TITLE
CtrlP search directory path?

### ISSUE THREAD

**Issue by microcosm** [skwp/dotfiles#522]
CtrlP is awesome for finding a file by name, using ,t

But if you have many files with the same name but under different directories, e.g.

/one/path/index.txt
/another/path/index.txt
/lots/and/lots/more/paths/index.txt

It can be a bit of a pain. Can it be configured to allow directory path searching?

**Comment by lfilho** [comment]
@microcosm see https://github.com/skwp/dotfiles/issues/745#issuecomment-286873861

Could you close this issue please? Thanks
