### ISSUE TITLE
Fugitive :Gblame doesnt work when vim is used in the terminal

### ISSUE THREAD

**Issue by samgranieri** [skwp/dotfiles#523]
I've got a fresh install of yadr running, and I open up mvim on the command line to a Rails app in a git repo and type the Fugitive Gblame command to look at the history, and then I get this command line backtrace. 
https://gist.github.com/samgranieri/405e4a7a6922563deed0

FWIW, Gblame works just fine in MacVim

**Comment by stevenbarragan** [comment]
The fix is correct, I added the plugin https://github.com/godlygeek/csapprox and it works fine.

**Comment by lfilho** [comment]
CSApprox is part of this repo now (it's been for a while - old thread), so I'm closing this issue. Cheers!
