### ISSUE TITLE
Overriding lightline

### ISSUE THREAD

**Issue by ianks** [skwp/dotfiles#539]
Has anyone been able to successfully override lightline settings? I have tried in the `.vimrc.after` and `.vimrc.before` with no luck. Only got it working by modify the base settings.

**Comment by fayimora** [comment]
@ianks did you manage to solve this? I'm trying to override lightline's colorscheme from solarized but it only works if I put my setting in the `vimrc` 😢 

`let g:lightline = {'colorscheme': 'onedark'}`

cc @skwp @kylewest

**Comment by fayimora** [comment]
currently lightline.vim has this:

```vim
let g:lightline = {
      \ 'colorscheme': 'onedark',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'fugitive': 'MyFugitive',
      \   'readonly': 'MyReadonly',
      \   'filename': 'MyFilename',
      \ },
      \ 'separator': { 'left': '⮀', 'right': '⮂' },
      \ 'subseparator': { 'left': '⮁', 'right': '⮃' }
      \ }

function! MyReadonly()
  if &filetype == "help"
    return ""
  elseif &readonly
    return "⭤ "
  else
    return ""
  endif
endfunction

function! MyFugitive()
  if exists("*fugitive#head")
    let _ = fugitive#head()
    return strlen(_) ? '⭠ '._ : ''
  endif
  return ''
endfunction

function! MyFilename()
  return ('' != MyReadonly() ? MyReadonly() . ' ' : '') .
       \ ('' != expand('%') ? expand('%') : '[NoName]')
endfunction

" Use status bar even with single buffer
set laststatus=2
```

What i want to do is override the colorscheme without loosing the other settings.

**Comment by kylewest** [comment]
`g:lightline` is a [dictionary](http://vimdoc.sourceforge.net/htmldoc/eval.html#Dictionary) so when you `let g:lightline = {'colorscheme': 'onedark'}` in your `.vimrc.after` you are overriding the entire dictionary with your new one (with just one key).

To change the value of one key in the dictionary you need to:

`let g:lightline['colorscheme']='onedark'` in your `.vimrc.after`.
