### ISSUE TITLE
Page-wise motion

### ISSUE THREAD

**Issue by ianks** [skwp/dotfiles#540]
I noticed `C-b` and `C-f` do not work in terminal vim. Was this mapping overridden on purpose?

**Comment by markrafael** [comment]
Does anyone else have this issue? I'm experiencing this as well.

**Comment by lfilho** [comment]
Only in terminal? Not in MacVim GUI? If so, looks like it might not be something that your terminal is overriding or preventing vim from using...

You can see where a map was last set by running `:verbose map` (for pluggins mappings) or `:help index` for default mappings, which seem to be the case.

Could you elaborate on this issue or close it? Thanks
