### ISSUE TITLE
error: unknown switch `r'

### ISSUE THREAD

**Issue by joshuacronemeyer** [skwp/dotfiles#543]
I'm using the most up to date yadr (f2fdd4506d7d4356d5b5a9e2e4c133e8b0740ed7). When I do :Gsearch I see an error "error: unknown switch `r'" and usage message from git grep.  It looks like greplace is expecting regular grep to be used but git grep is being used instead. For now i have replaced line 224 of greplace.vim with     let grep_opt  = '' and it's working again. Wondering if i'm doing something wrong here. Also not sure if I should report against yadr or greplace, but I'm leaning towards yadr. Thanks in advance.

**Comment by ramontayag** [comment]
I see this too on some installations. @joshuacronemeyer are you still doing this to fix it?

**Comment by lfilho** [comment]
@joshuacronemeyer and @ramontayag is this still happening? I've been using `Gsearch` since this issue was open and nobody else complained in all these years so I'm assuming it's (was) something local to your installation.

Hence I'm closing this issue. Feel free to reopen it. Cheers

**Comment by joshuacronemeyer** [comment]
It's working fine for me on my current setup! No longer using a modified greplace.vim

**Comment by ramontayag** [comment]
Sorry I no longer remember. An update or a different installation may have fixed it. I no longer see it. Thanks!
