### ISSUE TITLE
Anyone having issues with NerdTree when opening dirs?

### ISSUE THREAD

**Issue by ianks** [skwp/dotfiles#550]
Whenever I try to open a directory with vim( i.e. `vim ~/Desktop` ), NerdTree has a minor freakout. Want to see if this is a personal issue or a YADR issue.

I regularly update my plugins, so it might not apply to you if you do not.

![image](https://www.dropbox.com/s/zrounaqz3nwxkjh/Screenshot%202014-10-24%2014.15.12.png?dl=1)

**Comment by lfilho** [comment]
@ianks and @hoffi is this still happening? I believe not, right? (Never did to me anyways). So I'm taking the liberty of closing it. Feel free to reopen it otherwise
