### ISSUE TITLE
Detect Installation of MacPorts

### ISSUE THREAD

**Issue by Konafets** [skwp/dotfiles#558]
Please add a detection for MacPorts and avoid the installation of HomeBrew if MP is already installed.

**Comment by lfilho** [comment]
I can't answer for @skwp but I think this repo only supports `brew`. Unless @skwp changes his mind I think the best way for you to go is fork the repo to add MacPorts support.

Feel free to close this issue to help the maintainer out

**Comment by skwp** [comment]
Macports is dead 👍
