### ISSUE TITLE
Prompt duplication inside ruby project

### ISSUE THREAD

**Issue by phroa** [skwp/dotfiles#559]
Howdy.

So, my prompt looks pretty normal.

![screenshot 2014-11-03 07 24 03](https://cloud.githubusercontent.com/assets/6373176/4884661/e29dda2a-636d-11e4-938f-5940e5302145.png)

Until I cd into a ruby project, whereupon each line of prompt becomes two. I'm not pushing enter to get the multiple lines here. (also, entering a command starts at the beginning of a new line but when I hit enter, a prompt gets inserted and the command is in the normal spot for some reason. I really don't know)

![screenshot 2014-11-03 07 25 21](https://cloud.githubusercontent.com/assets/6373176/4884663/e99b564a-636d-11e4-88b7-d8ddc5c3ab71.png)

OS X 10.10, iTerm 2, most recent yadr as of now. Any ideas?

**Comment by lfilho** [comment]
Hi @phroa is this still happening? I believe not, right?
Closing this. Feel free to reopen it otherwise
