### ISSUE TITLE
Vim: gitcommit settings not working

### ISSUE THREAD

**Issue by ccll** [skwp/dotfiles#566]
I'm writing git commit message with Vim and noticed the `textwidth` setting is not working.
`:set textwidth` gives `textwidth=0`, if I manually `:set textwidth=72` it worked properly.
So it's either `textwidth` is not set at all or it's overwritten.

`:set filetype` gives `gitcommit`.
`:set formatoptions` gives `tcq`.
`:scriptsnames` shows related scripts are loaded correctly:

```
~/.yadr/vim/bundle/vim-git/ftplugin/gitcommit.vim
/usr/local/Cellar/vim/7.4.488/share/vim/vim74/ftplugin/gitcommit.vim
```

(they all set `textwidth=72` in their code)

Everything looks fine, so I guess something is overwriting the option.
Then I checked with `:verbose set textwidth` hoping to see which script is the last one to set this option, surprisingly I got another `textwidth=0`, no script names, nothing more. To my understanding it means this option is NOT set by any script at all.

Now I have no idea what to do, I'm not an Vim expert, so maybe I'm missing something here?

**Comment by skhilko** [comment]
Figured out why this is broken.

Spellchecking for gitcommit introduced in 38bcefdf6e069bdfa7482d0696ace984c6d888bc effectively disables processing of ```~/.yadr/vim/bundle/vim-git/ftplugin/gitcommit.vim``` setting ```b:did_ftplugin = 1```

Does it make sense to enable spellcheck globally and remove ```~/.yadr/vim/bundle/vim-git/ftplugin/gitcommit.vim```?

**Comment by lfilho** [comment]
Hey @ccll and @skhilko it's been a while now... Could you double check this is still happening? There were updates to this repo and vim-git plugins so maybe this is fixed now? It worked for me so I'm taking the liberty of closing the issue. Feel free to reopen it
