### ISSUE TITLE
zsh partial completion

### ISSUE THREAD

**Issue by fayimora** [skwp/dotfiles#568]
I don't really know when this started but at some point, partial completions stopped working. By partial completion I mean:

You type `cd `and press the up/down arrow keys. I'm usually able to scroll through previous cd commands. Did yadr remove this functionality at some point?

Cheers

**Comment by skwp** [comment]
Sorry guys I don't have any more info on what's going on here and this has been open too long. If other people are having this issue please reopen

**Comment by fayimora** [comment]
Thanks
