### ISSUE TITLE
Tab Autocomplete not work

### ISSUE THREAD

**Issue by nathanredblur** [skwp/dotfiles#572]
Hi, i have the latest updated version but i don't know what is wrong but on use zhs shell to navigate pressing tab not autocomplete.

example:
- folder1

$ cd fol<TAB>

Nothing happen. 

Thanks

**Comment by skwp** [comment]
I'm assuming this is not an issue any more. Afaik zsh, prezto, etc all work just fine with tabs.

**Comment by nathanredblur** [comment]
Finally I found the solution.
```rm -f ~/.zcompdump; compinit```

You can find more information here:
https://github.com/zsh-users/zsh-completions
