### ISSUE TITLE
Add git-up gem

### ISSUE THREAD

**Issue by ethanmad** [skwp/dotfiles#589]
Git-up is an alternative to "git pull" or that rebases rather than merging and updates all branches.

See [git-up on GitHub](https://github.com/aanand/git-up) for code and details

It's a great gem and in my opinion should be a default git command. Adding it to yadr would allow (1) all of us to install it without extra effort and (2) will help beginners (or everyone, really) contribute to yadr and other open-source projects because they won't have to worry about a messy commit log full of merge commits.

**Comment by lfilho** [comment]
Why not make an alias to `git pull --rebase`? The difference being that it would not update all the local branches... Which, in my opinion, is the desired behaviour: I work in a team with many developers and active branches... I don't wanna be rebasing all those branches everytime...

**Comment by ethanmad** [comment]
I see your point, but don't you need to update all branches before pushing back to a remote repository? If you only `git pull --rebase` one branch and try to push, git will yell at you and tell you to update the other branches.  Even if you only want to update your branch most of the time, git-up could still be convenient when you want to push your changes.

**Comment by skwp** [comment]
git push at least in our current config only pushes the current branch you're on. I think it's unexpected to push all the branches and probably not desirable most of the time.

**Comment by ethanmad** [comment]
Oh, I didn't realize. That makes a lot more sense than pushing all the
branches (which is I think the default git config).

**Comment by skwp** [comment]
Yeah I disagree pretty strongly with git's new default :(

**Comment by lfilho** [comment]
Yeap, mine too just pushes the current one. Which new config is that?

**Comment by ethanmad** [comment]
I think if you're using yadr then you won't be affected by the default git
config because yadr overrides it. Actually, I looked at the git 2.0 release
notes and it seems like the git push used to push all branches, but now it
only pushes the current branch. Maybe one of my computers has outdated git.

**Comment by skwp** [comment]
Ah, yes git 2.0 uses the default of 'simple' which is current branch. YADR's config sets it to be 'upstream' which I think is the same

**Comment by ethanmad** [comment]
So I brought this realization with the developer of git up and he
admitted/realized that it doesn't add much beyond the mentioned alias with
git 2.0. So I guess we can close this issue.

**Comment by skwp** [comment]
Cool, btw `gplr` is the yadr alias for git pull --rebase

**Comment by ethanmad** [comment]
Thanks, I'll use that and remove git up from my computer.
