### ISSUE TITLE
syntastic ruby checker stopped accepting Ruby 2.1 named args

### ISSUE THREAD

**Issue by skwp** [skwp/dotfiles#590]
Not sure if this is our fault or what, but somehow ruby 2.1 required named args are blowing up

example

def foo(bar:)
end

is causing syntastic to report it as an error. ruby specs on this will pass

**Comment by skwp** [comment]
I think this is related to syntastic not respecting rvm

**Comment by jby** [comment]
Have you had a look at this?

https://rvm.io/integration/vim

Apparently one can experience strangeness with rvm and vim on OS X.

There's a couple of issues over at Syntastic about this (one being mine):

https://github.com/scrooloose/syntastic/issues/1407
https://github.com/scrooloose/syntastic/issues/1310

I haven't had the time to investigate any further though.

**Comment by JoshTGreenwood** [comment]
For anyone who finds this issue later, here's a one liner for syntactic to respect Rbenv's current ruby:
```
:let g:syntastic_ruby_mri_exec = “/Users/#{Your Username}/.rbenv/shims/ruby"
```

**Comment by lfilho** [comment]
Is this still an issue, @skwp ?

**Comment by skwp** [comment]
I've switched to rbenv actually, planning to switch this project over to that. Seems simpler
