### ISSUE TITLE
NERDTreeFind statically forced to 30 width

### ISSUE THREAD

**Issue by blittle** [skwp/dotfiles#594]
https://github.com/skwp/dotfiles/blob/ee6e5b959047d13a45f1071967d6760526716ceb/vim/settings/yadr-keymap.vim#L78

Shouldn't this pull from `g:NERDTreeWinSize`?

UPDATED:
It properly pulls from the window size variable if I change that line to:
```
nnoremap <silent> <C-\> :NERDTreeFind<CR>:vertical<CR>
```

**Comment by skwp** [comment]
I'm ok with changing it to the window size variable, or rather defining that variable in yadr as a default to be 30. What do you think?

**Comment by blittle** [comment]
Either way, I'd just like the ability to change the default size without having yadr forcing it to another size.

**Comment by blittle** [comment]
@skwp it looks like yadr is already defaulting `g:NERDTreeWinSize` to 30. See https://github.com/skwp/dotfiles/blob/master/vim/settings/NERDtree.vim#L4

Simply by removing the static value of 30 in the key mapping should work. Could we get this merged?

**Comment by skwp** [comment]
Fixed in #595

**Comment by blittle** [comment]
Thanks @skwp !
