### ISSUE TITLE
MacVim & Solarized background=light gives strange results.

### ISSUE THREAD

**Issue by chestone** [skwp/dotfiles#597]
After installing yadr I tried to switch to the light version of Solarized in MacVim and found some funky results shown below.

The end of my .vim/settings/yadr-appearance.vim is below.

```
  1 " Make it beautiful - colors and fonts
  2
  3 if has("gui_running")
  4   if has("gui_macvim")
  5     set background=light
  6     colorscheme solarized
  7   endif
  8
  9   "tell the term has 256 colors
 10   set t_Co=256
 11
 12   " Show tab number (useful for Cmd-1, Cmd-2.. mapping)
 13   " For some reason this doesn't work as a regular set command,
 14   " (the numbers don't show up) so I made it a VimEnter event
 15   autocmd VimEnter * set guitablabel=%N:\ %t\ %M
 16
 17   set lines=60
 18   set columns=190
 19
 20   if has("gui_gtk2")
 21     set guifont=Inconsolata\ XL\ 12,Inconsolata\ 15,Monaco\ 12
 22   else
 23     set guifont=Inconsolata\ XL:h17,Inconsolata:h20,Monaco:h17
 24   end
 25 else
 26   let g:CSApprox_loaded = 1
 27
 28   " For people using a terminal that is not Solarized
 29   if exists("g:yadr_using_unsolarized_terminal")
 30     let g:solarized_termcolors=256
 31     let g:solarized_termtrans=1
 32   end
 33 endif
 34
 35 set background=light
 36 colorscheme solarized
```

I have also tried adding the background & colorscheme to my .gvimrc, but to no success. Any help would be appreciated.

![vim_broken_solarized](https://cloud.githubusercontent.com/assets/26659/5828669/dc18e038-a0bb-11e4-9080-85d9c7e2153f.jpg)

**Comment by chestone** [comment]
I've also tried adding these options 'set background=light' & 'colorscheme solarized' to my .vimrc.after and still the same result.

**Comment by romeroabelleira** [comment]
Setting Solarize > Background > Light Background makes the issue disappear, but the settings don't persist.
![screen shot 2015-01-27 at 10 45 27](https://cloud.githubusercontent.com/assets/108562/5916471/f396ccba-a611-11e4-924d-9d7dcf5c4d52.png)

**Comment by chestone** [comment]
Yep. I am experiencing the same issue. I looked up the file where the menu is built 'bundle/vim-colors-solarized/colors/solarized.vim' and this is what that menu item runs. 
'amenu &Solarized.&Background.&Light\ Background  :set background=light \| colorscheme solarized<CR>'

I've tried running this in my .vimrc.after file and still see the same issue.

**Comment by brandonaaron** [comment]
I'm using the light theme with yadr successfully. I've modified my .vimrc (in my fork of the project... I assume adding to .vimrc.after should work fine as well) in the following way.

    let g:yadr_disable_solarized_enhancements = 1
    if !has("gui_running")
      let g:solarized_termtrans=1
    endif
    set background=light
    colorscheme solarized

**Comment by skwp** [comment]
You might have to move the disable_solarized into .vimrc.before and the rest into the after

**Comment by chestone** [comment]
That works! Thank you so much @brandonaaron!

**Comment by romeroabelleira** [comment]
@brandonaaron as @skwp noted, this worked perfectly:

~/.vimrc.before

    let g:yadr_disable_solarized_enhancements = 1

~/.vimrc.after

    if !has("gui_running")
      let g:solarized_termtrans=1
    endif
    set background=light
    colorscheme solarized

**Comment by chestone** [comment]
:+1:
