### ISSUE TITLE
Cucumber step definitions are not recognized

### ISSUE THREAD

**Issue by NilsHaldenwang** [skwp/dotfiles#60]
When I am in a feature within a rails 3 app vim does not recognize my step definitions.

The feature file is located at `features/some_folder/some_feature.feature`, the step definitions are located at `features/step_definitions/some_step_definitions.rb`.

I am getting lots of warnings of the type Cucumber::Undefined in a quickfix window for alle the steps used in the feature. They are saying the steps are undefined, so something is wrong somewhere but I have not been able to figure out where.

**Comment by sonianand11** [comment]
Here is the sample config/cucmber.yml file that works for me.

```
<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip"
other_opts = "--require features/step_definitions"
%>
#default: <%= std_opts %> features
default: <%= std_opts %> <%= other_opts%> features
wip: --tags @wip:3 --wip features
rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
```

**Comment by sonianand11** [comment]
I have fixed error using following instruction : https://github.com/tpope/vim-cucumber/issues/30
