### ISSUE TITLE
Question: disable error pane for golang

### ISSUE THREAD

**Issue by markburns** [skwp/dotfiles#601]
Sorry this is pure laziness on my part, but part of the reason why I use your repo is that same laziness and enjoying things just working. I had a brief look into it but couldn't find out how to disable it.

I'm hoping that you just know off the top of your head hence I'm asking the question.

I'm going through the go koans and I get error messages that are irrelevant to what I am doing right now. I'm sure I want them enabled for actually writing go code, but I am just starting out so would rather keep the screen space.

Screenshot so you know what I mean:

![screen shot 2015-02-08 at 10 46 03](https://cloud.githubusercontent.com/assets/104158/6096083/fabc739c-af7f-11e4-94cb-9cb2b650bc61.png)

**Comment by skwp** [comment]
The errors are coming from a plugin called syntastic (https://github.com/scrooloose/syntastic). Please see the help file ther efor how to enable or disable them. Thanks
