### ISSUE TITLE
"is a directory" messages when viming a directory

### ISSUE THREAD

**Issue by bachya** [skwp/dotfiles#614]
Hello!

Previously, running vim on a directory (e.g., `vim .`) would pull up a directory listing and allow for browsing. Now, it doesn't appear to work: using the above command, I get:

`"." is a directory` (with a blank screen thereafter)

Thanks!

**Comment by stevepm** [comment]
I was just about to make an issue for this. I'm getting the same thing.

**Comment by JoshTGreenwood** [comment]
Has anyone found a solution to this?

**Comment by minyoungjun** [comment]
I am in same trouble...

**Comment by jamespjh** [comment]
I'm experiencing this.

**Comment by gmaghera** [comment]
I am running into this issue too.  In my case '"." is a directory' shows up twice.

**Comment by lfilho** [comment]
Hello everyone, is this still an issue (maybe vim releases have been made since then...). Make sure you're using MacVim's version of `vim` (which is what this repo uses).

I just tried it and it works fine for me (NerdTree opens) so I'm going ahead and close this issue. Feel free to reopen it
