### ISSUE TITLE
Git does not use mvim

### ISSUE THREAD

**Issue by bmanuel** [skwp/dotfiles#617]
Git commands that open an editor (ie `git commit` without -m) open the builtin vim despite `alias vim="mvim -v"`

**Comment by bmanuel** [comment]
This is an issue because the built-in version of vim does not have lua support enabled. This causes the lua warning to appear every time.

**Comment by jby** [comment]
Install macvim with '--override-system-vim', that will probably solve this.

**Comment by bmanuel** [comment]
That seems to have done it. I am interested in why that didn't work in the first place since that flag is part of the install script. Support was added in this commit https://github.com/skwp/dotfiles/commit/6c54f2c84a32f1119c29d723b30f500db2073e8e, so it was certainly there when I set up this computer. If I am the only one having this issue, I would definitely consider it closed at this point.

**Comment by jby** [comment]
One reason why it didn't work in the first place might be that you hadn't accepted the Xcode license agreement before setting up yadr the first time.
Homebrew requires that to build macvim - I just set up a new mac and wondered why it didn't build macvim on install of yadr until I tried manually.

**Comment by jby** [comment]
Oh, and you can close the issue yourself.

**Comment by bmanuel** [comment]
Is there a way to guard against that happening? Or maybe something should just be included in the readme.
