### ISSUE TITLE
grep: warning: GREP_OPTIONS is deprecated

### ISSUE THREAD

**Issue by petRUShka** [skwp/dotfiles#620]
I constantly catch following warning

    grep: warning: GREP_OPTIONS is deprecated

The cause of it is the following line:

    .yadr/zsh/prezto/modules/environment/init.zsh:42:
        export GREP_OPTIONS='--color=auto'

Please see corresponding issues in oh-my-zsh:

https://github.com/robbyrussell/oh-my-zsh/issues/3340
https://github.com/robbyrussell/oh-my-zsh/pull/3341
https://github.com/robbyrussell/oh-my-zsh/issues/3343

P.S. Linux, grep (GNU grep) 2.21

**Comment by JacobDorman** [comment]
Updating to latest prezto fixes the problem.
```
cd zsh/prezto
git checkout master
git pull && git submodule update --init --recursive
cd ../../
rake update
```

**Comment by petRUShka** [comment]
You are right. That solved the problem. Thanks!

**Comment by skwp** [comment]
I just pushed a commit to yadr that points to prezto master
