### ISSUE TITLE
vim quickfix panel doesnt close with ,qc after error

### ISSUE THREAD

**Issue by rocknrollMarc** [skwp/dotfiles#632]
Please give me a way to close that damn window :) I hate it everytime it doesnt understand my html it opens, which is very nice but I would love to close it especialy in go and html.

Thanks guys

**Comment by skwp** [comment]
the syntastic window is not the quickfix window..try `:lclose`. You can map that if it annoys you. also the universal `Q` should work

**Comment by rocknrollMarc** [comment]
cool thanx ill try that Q doesnt work on go files
