### ISSUE TITLE
Name collision for Plugin christoomey/vim-tmux-navigator

### ISSUE THREAD

**Issue by cdenneen** [skwp/dotfiles#634]
Error detected while processing function vundle#config#bundle..<SNR>10_check_bundle_name:
line    2:
Vundle error: Name collision for Plugin christoomey/vim-tmux-navigator. Plugin christoomey/vim-tmux-navigator previously used the name "vim-tmux-navigator". Skipping Plugin christoomey/vim-tmux-navigator.

**Comment by fizz** [comment]
You probably have vim-tmux-navigator listed in two .vundle files, check your ~/.vundles.local or ~/.vim/.vundles.local

**Comment by cdenneen** [comment]
I don't have a .vundles.local and nothing in either directory
I have a bundle/vim-tmux-navigator directory and vundles/vim-improvments.vundle that has 'Bundle "christoomey/vim-tmux-navigator"' but not duplication that I can find and I haven't added anything manually myself
Doing a search in all of yadr I find:

.yadr/vim/settings/yadr-keymap.vim:94:" NOTE: This has moved to vim/settings/vim-tmux-navigator.vim.
.yadr/vim/vundles/vim-improvements.vundle:12:Bundle "christoomey/vim-tmux-navigator"

**Comment by skwp** [comment]
Try `rake update` and make sure you have no local changes? I would also try to rm -rf ~/.vim/bundle/*vim-tmux*

**Comment by cdenneen** [comment]
@skwp i've run rake update and also removed .vim/bundle/vim-tmux-navigator and still getting error:

```
Error detected while processing function vundle#config#bundle..<SNR>10_check_bun
dle_name:
line    2:
Vundle error: Name collision for Plugin christoomey/vim-tmux-navigator. Plugin c
hristoomey/vim-tmux-navigator previously used the name "vim-tmux-navigator". Ski
pping Plugin christoomey/vim-tmux-navigator.
```
