### ISSUE TITLE
gf stopped working?

### ISSUE THREAD

**Issue by skwp** [skwp/dotfiles#635]
recent bundle update caused gf to stop working

**Comment by emaiax** [comment]
same here. :sob:

**Comment by skwp** [comment]
Not sure what's affecting this. It's a very standard mapping that's in all the vim tips. The best I can do is unmap gf and let people use the native functionality

**Comment by skwp** [comment]
It looks like rails.vim used to map gf but for some reason that mapping is missing

**Comment by emaiax** [comment]
Does the problem has any relation with this commit? https://github.com/tpope/vim-rails/commit/ab914b271e03ea5ac3cedb9b726f8f6ee1cd5d85

**Comment by corroded** [comment]
What's the status for this? Is there a quick workaround?

**Comment by emaiax** [comment]
@skwp thoughts? it's been a pain :/

**Comment by corroded** [comment]
i miss my `gf` :broken_heart:

**Comment by skwp** [comment]
my gf is now working, whatever it was seems to have fixed itself with plugin updates...

**Comment by emaiax** [comment]
@skwp I removed all plugins on `~/.vim/bundle` and then reinstalled. nothing's changed. 😭
