### ISSUE TITLE
Errors when opening mvim after updating mvim

### ISSUE THREAD

**Issue by pdebelak** [skwp/dotfiles#638]
I get the following error now:

    Error detected while processing /Users/pdebelak/.yadr/vim/bundle/AutoTag/plugin/autotag.vim:
    line  229:
    E887: Sorry, this command is disabled, the Python's site module could not be loaded.

It still opens normally, but I'm not sure what changed to cause this error.

**Comment by skwp** [comment]
what's the mvim verison?

**Comment by pdebelak** [comment]
Turns out the issue was that when brew updated macvim it didn't use a version with lua. I followed the instructions in the README to reinstall and now everything is back to normal.
