### ISSUE TITLE
Entering vim for the first time will leave lots of empty line

### ISSUE THREAD

**Issue by ldong** [skwp/dotfiles#640]
Hi there,

I use skwp's dotfiles, and I run into this behavior when entering vim for the first time, and exit vim. There will be lots of empty lines in the console.

Here are the screenshots.
![spaces](https://cloud.githubusercontent.com/assets/5491695/8888744/53964a0c-326f-11e5-9904-ad89150c2b0a.gif)

if I disable all vim plugins by typing `vim -u NONE`, it stop occurring. So, it is not specific to `zsh` nor `bash`.

I wonder if anyone can help on figuring out the cause of that strange behavior. Thank you in advance.

**Comment by skwp** [comment]
This is going to be a pretty deep rabbithole to figure out for a relatively minor effect. I don't think this should be here as an issue. Please continue conversation with other users here https://groups.google.com/forum/#!forum/yadr-users

**Comment by ldong** [comment]
@skwp I've found out the reason why it keeps occurring. Please see my [PR](https://github.com/skwp/dotfiles/pull/643) Thank you.

**Comment by skwp** [comment]
nicely done thanks
