### ISSUE TITLE
zsh plugins

### ISSUE THREAD

**Issue by pertrai1** [skwp/dotfiles#642]
I need to add `virtualenv` and `virtualenvwrapper` but don't see where I would add just like I would to .zshrc for oh-my-zsh?

**Comment by skwp** [comment]
whatever you need to do you should be able to do in ~/.zshrc.after/whatever.zsh - just make a script in there and do your thing? You might want to vet this with other folks in discussion https://gitter.im/skwp/dotfiles https://groups.google.com/forum/#!forum/yadr-users
