### ISSUE TITLE
Vim Visual mode highlight color is different in gui and cli mode (MacVim)

### ISSUE THREAD

**Issue by yjlintw** [skwp/dotfiles#646]
The MacVim visual mode highlight color is different in gui and cli mode. 
In cli mode it is set to blue ( ctermbg=021), but in gui mode it is set to grey which makes it hard to read.

It can be easily fixed by editing the `.vim/setting/solarized.vim` line 71
from

``` VimL
hi! Visual ctermbg=021
```

 to:

``` VimL
hi! Visual ctermbg=021 guibg=#0000FF
```

https://github.com/peacedove/dotfiles/commit/d3309d3f3d571268bc081349005b2af64dae54aa

**Comment by lfilho** [comment]
Seems like this was solved by the referenced links above. Closing it.
