### ISSUE TITLE
tab filename completion in terminal windows not working

### ISSUE THREAD

**Issue by akashshinde** [skwp/dotfiles#649]
As root user,I have installed this dotfile,everything is working fine except when I type cd and wanted to get any file,I am just typing initials of file and hitting tab which is giving me nothing.
Please look into this

**Comment by nuin** [comment]
Same here.

**Comment by andremalan** [comment]
The same thing happens to me. I tried reinstalling and nothing changed. Did anybody find a solution?

**Comment by lfilho** [comment]
Could you elaborate more and add reproducing steps? I'm not sure I got your problem. Can one reproduce this without installing the repo as a root user? Thanks

**Comment by lfilho** [comment]
ping @akashshinde @petemounce @nuin
