### ISSUE TITLE
chsh: /bin/zsh is an invalid shell

### ISSUE THREAD

**Issue by rakesh-sankar** [skwp/dotfiles#650]
Title says it all.

I have followed the instruction to install YADR on Ubuntu 14.04 and the change shell command didn't succeed, it reported that the zsh is an invalid shell and I have also verified that zsh isn't there in /bin/zsh.

**Comment by calebkiage** [comment]
You need to install the zsh shell. On ubuntu, you can do this by running the following command:
`sudo apt install zsh`

**Comment by bridgesense** [comment]
On Ubuntu?.. and zsh-dev or you'll be in for a world of hurt if installing remotely.

**Comment by lfilho** [comment]
@rakesh-sankar Is this still happening? I have run this repo's installation for some friends using linux and it all worked fine. Can you double check the following lines and see if there's something missing for Linux? https://github.com/skwp/dotfiles/blob/master/Rakefile#L277-L290

Cheers

**Comment by rakesh-sankar** [comment]
Let me check this out and confirm and close this issue ASAP.

**Comment by lfilho** [comment]
ping @rakesh-sankar
