### ISSUE TITLE
can't toggle nerdTreee in VIM

### ISSUE THREAD

**Issue by Pushplaybang** [skwp/dotfiles#652]
opens and jumps to the current file with Ctrl-\ but Cmd-shift-N does naught...... any ideas?

**Comment by R3liant** [comment]
Do you happen to be using PuTTY?

**Comment by Pushplaybang** [comment]
nope, iterm2 on OSX.

**Comment by powersjcb** [comment]
Currently have the same issue. iterm2, osx

**Comment by erickwilder** [comment]
Same behaviour here.

**Comment by Pushplaybang** [comment]
yeah not really sure how to tackle this, I can toggle it by typing out the full command, which sort of defeats the point.

**Comment by R3liant** [comment]
I believe what is happening is that iterm2 (in my case gnome-terminal) is not sending the alt / Cmd key as the meta key, its sending it as a escape encoded sequence. See http://vim.wikia.com/wiki/Get_Alt_key_to_work_in_terminal. Not sure how to go about fixing this in a reliable manner.

**Comment by Pushplaybang** [comment]
interesting.

**Comment by skwp** [comment]
the cmd key is only reliable in macvim as far as I know. As per the docs yadr is macvim optimized. You can easily make your own mapping for nerdtree:

`map ,nt :NERDTreeToggle<CR>`

**Comment by Pushplaybang** [comment]
thanks @skwp -how does one launch "macvim"  i was unaware there was a distinction.  I always believed in one true vim.

sorry for the noob question ahead of time.

**Comment by Pushplaybang** [comment]
nvvrmnd.

```bash
   mvim
```
