### ISSUE TITLE
Installing on Ubuntu breaks SSH - potentially serious

### ISSUE THREAD

**Issue by aliostad** [skwp/dotfiles#657]
I installed yadr on my Ubuntu servers (Ubuntu 14.04.2 LTS) and then realised that I can no longer SSH to the boxes. Luckily already had an open connection to the boxes so after hours of digging, I found out that the problem was my default terminal in `passwd` was set to `/bin/zsh` while the only zsh file was at `~/.yadr/zsh`. And I realised that the file does not exist so I did `apt-get install zsh` and it fixed it.

**This can potentially render servers unusable by losing the ability to login.**

**Comment by skwp** [comment]
yadr does not officially support ubuntu installs. please supply a PR if you'd like this fixed, thanks

**Comment by aliostad** [comment]
OK thanks. Unfortunately my linux knowledge is not enough for me to do this safely :)

**Comment by KristerV** [comment]
oooh.. this is why it's broken... uhh. mentioning this would be good.

**Comment by bridgesense** [comment]
Other than the missing the zsh pre-requisite, there isn't anything wrong with Yadr running in Ubuntu.
