### ISSUE TITLE
Persistent undo is broken

### ISSUE THREAD

**Issue by daxgames** [skwp/dotfiles#659]
Need to remove ! from line 52 of vimrc.

**Comment by minhoolee** [comment]
Can confirm that this worked for me.

**Comment by daxgames** [comment]
This has been broken for months, removing the ! Does fix it.

**Comment by lfilho** [comment]
Hey @daxgames I believe the lines might have moved in the mean while... Could you just submit a PR fixing the issue?

**Comment by daxgames** [comment]
Done #758
