### ISSUE TITLE
Fixing zsh/aliases.zsh for ls aliases

### ISSUE THREAD

**Issue by skrisna** [skwp/dotfiles#660]
I think the correct code for ls aliases in zsh/aliases.zsh is --

```
 if [[ $platform == 'linux' ]]; then
-  alias ll='ls -alh --color=auto'
-  alias ls='ls --color=auto'
+  alias ll="${aliases[ls]:-ls} -alh --color=auto"
+  alias ls="${aliases[ls]:-ls} --color=auto"
 elif [[ $platform == 'darwin' ]]; then
-  alias ll='ls -alGh'
-  alias ls='ls -Gh'
+  alias ll="${aliases[ls]:-ls} -alGh"
+  alias ls="${aliases[ls]:-ls} -Gh"
 fi
```

The reason is that the ls alias already gets initialized in ./zsh/prezto/modules/utility/init.zsh. The aliases in zsh/aliases.zsh overwrites the previous aliases.

**Comment by lfilho** [comment]
I'm not sure I understand the issue. What's the problem in overwriting prezto's aliases with the ones we have here?
