### ISSUE TITLE
Windows OS Option?

### ISSUE THREAD

**Issue by pertrai1** [skwp/dotfiles#662]
Would there be any possibility of using this on a Windows machine? If not, do you know of any similar projects like you have that are for Windows?

Thank you,

Rob

**Comment by DanielGGordon** [comment]
I'm wondering the same, if this could somehow be integrated with Git Bash, Mintty, Cygwin, or Msysgit2 or something like that.

**Comment by bridgesense** [comment]
VMWare into your favorite distro or Mac OS.  It might not be the best solution, but why not?  I can run YADR natively, but I still have boxes I work in tailored for specific tasks.  Although it's hard to ignore the fact that Windows is slowly creeping up to the lead for server distributions.  I guess all those young gamers have turned into MCSE.

**Comment by lfilho** [comment]
As per noted in the README file, we can only support OSX at the moment.

All support towards Windows or Linux must come as contributions from the community as the maintainers only have OSX machines to test things out now.

If you find a clean way to support it, feel free to contribute back to us by opening a PR! :-) Thanks
