### ISSUE TITLE
.inputrc breaks ^A and ^E in Python interactive shell

### ISSUE THREAD

**Issue by april** [skwp/dotfiles#663]
This might be a WONTFIX, since the project does try to vimify everything, but the .inputrc file that comes with YADR breaks the ability to use control-a (beginning-of-line) and control-e (end-of-line) inside of the Python interactive shell.  Given that those keybindings _do_ work for zsh, I thought this might be a bug to be fixed.

**Comment by lfilho** [comment]
Does vim-style navigation works, though? Like <kbd>0</kbd> and <kbd>$</kbd>...

This is probably a WONTFIX indeed as not only breaks the vimification, but also it seems specific to Python REPL, and different REPL could adopt different keymaps, so on and so forth...

Feel free to reopen the issue if need to
