### ISSUE TITLE
tmux list sessions is gone

### ISSUE THREAD

**Issue by ptgamr** [skwp/dotfiles#665]
I used to use "s" to switch between sessions (it list the sessions, so I can choose the right session to attach), now I'm not able to do that anymore because in dotfiles, `s` is binded to split a horizontal pane.

I did remove `bind-key s split-window -p 50 -c "#{pane_current_path}"` in `.tmux.conf`, but has no effect at all.

Any idea how to restore that functionality?

**Comment by fayimora** [comment]
@ptgamr were you able to resolve this?

cc @skwp @kylewest

**Comment by fayimora** [comment]
p.s I added the binding below to my `~/.tmux.conf.user` 

```tmux
unbind l
bind l list-sessions
````
