### ISSUE TITLE
Add zoom awareness to tmux conf

### ISSUE THREAD

**Issue by mmlac-bv** [skwp/dotfiles#673]
The window_zoomed_flag can be used to check the status of whether a pane is zoomed. The code below changes the color on zoom and adds [ ] around the process name.

    set -g window-status-current-format "#{?window_zoomed_flag,#[bg=colour9],#[bg=colour39]}#[fg=colour234]⮀#[fg=black,noreverse,bold] #I: #{?window_zoomed_flag,[,}#W#{?window_zoomed_flag,]#[fg=colour9],#[fg=colour39]} #[bg=colour234,nobold]⮀"

normal / one pane:
<img width="164" alt="screen shot 2015-10-29 at 12 05 21 am" src="https://cloud.githubusercontent.com/assets/4039894/10812179/d6027a4a-7dd0-11e5-820b-3965dacde49a.png">

zoomed pane in a multi-pane window:
<img width="128" alt="screen shot 2015-10-29 at 12 05 31 am" src="https://cloud.githubusercontent.com/assets/4039894/10812178/d6019ed6-7dd0-11e5-9dcb-6bbc39c9f0f7.png">

**Comment by skwp** [comment]
Just merged a PR that did this
