### ISSUE TITLE
Generating rails migration with polymorphic modifier

### ISSUE THREAD

**Issue by DavidVII** [skwp/dotfiles#678]
Hello, not sure if this is the right place to post this, but I'm only seeing this issue when using yadr. I'm getting unexpected behavior when generating a rails migration or model with the polymorphic modifier. Consider the following:

```
rails generate migration CreateTaggings taggable:references{polymorphic}
```

This will generate the following migration

``` ruby
class CreateTaggings < ActiveRecord::Migration
  def change
    create_table :taggings do |t|
      t.referencesc :taggable
      t.referencesh :taggable
      t.referencesi :taggable
      t.referencesl :taggable
      t.referencesm :taggable
      t.referenceso :taggable
      t.referencesp :taggable
      t.referencesr :taggable
      t.referencesy :taggable
    end
  end
end
```

If I don't use yadr then everything works as expected so I'm lead to believe something in these dotfiles is the culprit. If I don't add the polymorphic modifier then the migration file is generated as expected (without the polymorphic stuff). Maybe something to do with curly braces?

**Comment by lfilho** [comment]
I'm also assuming it's something with the curly braces or the way zsh deals with them.
We didn't have more complaints about this and it's been a while, so I'm taking the liberty of closing this issue, ok? Feel free to reopen it if needed
