### ISSUE TITLE
Vim does not suspend after update

### ISSUE THREAD

**Issue by m0n9oose** [skwp/dotfiles#679]
I've updated yadr last night and now i can't send vim to background with Ctrl-Z

after hitting ctrl-z i see error `E42: No errors`. Command `:sus` works fine.

<img width="216" alt="screen shot 2015-11-24 at 19 32 23" src="https://cloud.githubusercontent.com/assets/1478556/11373186/2454afda-92e2-11e5-967a-6cb3a3265907.png">

**Comment by m0n9oose** [comment]
```
Mac OS X 10.11.1
iTerm2 Build 2.9.20151111
```

```
~/d/sh2 ❯❯❯ vim --version                                                                                                                                                  master
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2015 18:28:54)
MacOS X (unix) version
Included patches: 1-930
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_binary
+arabic          +find_in_path    -mouse_sysmouse  +tag_old_static
+autocmd         +float           +mouse_urxvt     -tag_any_white
+balloon_eval    +folding         +mouse_xterm     +tcl
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +fullscreen      -mzscheme        +textobjects
+cindent         -gettext         +netbeans_intg   +title
+clientserver    -hangul_input    +odbeditor       +toolbar
+clipboard       +iconv           +path_extra      +transparency
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
+farsi           +mouse_netterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      -I/System/Library/Frameworks/Tcl.framework/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework Cocoa  -pagezero_size 10000 -image_base 100000000 -L/usr/local/lib -lluajit-5.1 -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby
```

**Comment by m0n9oose** [comment]
seems i figure out why it happens:

after update/reinstall yadr create alias 
```
~/d ❯❯❯ which vim
vim: aliased to mvim -v
```

**Comment by m0n9oose** [comment]
anybody?

**Comment by christophermlne** [comment]
i'm having this issue as well

**Comment by m0n9oose** [comment]
@skwp any thoughts?

**Comment by masa-beheim** [comment]
Same here.

**Comment by westhechiang** [comment]
Same here too

**Comment by portOdin** [comment]
It's a problem with Syntastic. Though I can't recall how I fixed it at the moment.

**Comment by christophermlne** [comment]
@portOdin what did you determine it was a problem with Syntastic? how did you debug this? maybe we can track this down because it's driving me nuts

**Comment by portOdin** [comment]
Sorry for taking so long. I greped yadr for the <C-Z> key binding and found it mapped within ~/.yadr/vim/yadr-keymap.vim to :cp, which is used to navigate the quick fix error list (not actually a Syntastic command, so I was wrong about that). You can just remove or change those mappings and <C-Z> works again.

![screen shot 2015-12-29 at 1 03 04 am](https://cloud.githubusercontent.com/assets/5838941/12030156/71bf8f64-adc8-11e5-928a-62110310bbec.png)

**Comment by christophermlne** [comment]
@portOdin thanks!

**Comment by m0n9oose** [comment]
Great! It works! How can i apply this solution permanently? I mean just comment this line in config will be override on next skwp update

**Comment by portOdin** [comment]
`echo "nnoremap <silent> <C-z> :sus<CR>" >> ~/.vimrc.before`

That'll append to .vimrc.before the remapping for the suspend command. It'll create the file if it doesn't exist.

**Comment by m0n9oose** [comment]
@portOdin sorry, but it doesn't work for me.

**Comment by portOdin** [comment]
Sorry, try this. `echo "nnoremap <silent> <C-z> :sus<CR>" >> ~/.vimrc.before` Overrides should go into `~/.vimrc.after`, not `~/.vimrc.before`, I believe.

**Comment by westhechiang** [comment]
confirming that @portOdin 's solution works!

**Comment by skwp** [comment]
sorry all, yadr is optimized for MacVim - didn't think about the usage of ctrl-z in terminal, that is inded a problem

**Comment by 6ewis** [comment]
should we send a PR?

**Comment by m0n9oose** [comment]
Bump

**Comment by lfilho** [comment]
ping @skwp 

I also removed that mapping in my fork. These are the mappings I use for quickfix window stuff (i found the mnemonics to be easier to remember and more coherent with each other):

```vim
" Mnemonic: *q*uickfix *c*lose
nnoremap <silent> <leader>qc :cclose<CR>
" Mnemonic: *q*uickfix *o*pen
nnoremap <silent> <leader>qo :copen<CR>
" Mnemonic: *q*uickfix *n*ext
nnoremap <silent> <leader>qn :cn<CR>
" Mnemonic: *q*uickfix *p*revious
nnoremap <silent> <leader>qp :cp<CR>
" Mnemonic: *q*uickfix */*
nnoremap <silent> <leader>q/ :execute 'vimgrep /'.@/.'/g %'<CR>:copen<CR>
" Mnemonic: *q*uickfix *g*rep
nnoremap <silent> <leader>qg :execute "Rg --smart-case '" . substitute(substitute(substitute(@/, "\\\\<", "\\\\b", ""), "\\\\>", "\\\\b", ""), "\\\\v", "", "") . "'"<CR>
```

**Comment by skwp** [comment]
Oh man, yeah that sucks. I really like the one key mappings (Ctrl-x/Ctrl-z) because you can quickly scroll the quickfix list. Can we find some other ctrl- mappings for those that don't interfere?

How about C-a and C-s?

**Comment by lfilho** [comment]
I think C-s don't work easily on terminals. And C-a, IIRC, belongs to tmux.

I don't navigate that much and that often on the quickfix window so my mappings, at least so far, work fine for me. Open to suggestions too 😇

**Comment by lfilho** [comment]
Oh, I also use the original C-x a lot (decrement numbers)... That's why I always try to avoid replacing default behaviour/keymaps in vim...

**Comment by domi91c** [comment]
Considering C-x is already replaced by these mappings, you could do C-a C-x?

**Comment by skwp** [comment]
yeah c-a is tmux and also increment number

**Comment by lfilho** [comment]
c-shift-x && c-shift-z? :man_shrugging:

**Comment by skwp** [comment]
That would be fine (c-X, c-Z) with the shift

-- 
Yan Pritzker
https://twitter.com/skwp

On June 20, 2017 at 12:27:28 PM, Luiz Gonzaga dos Santos Filho (
notifications@github.com) wrote:

c-shift-x && c-shift-z? 🤷‍♂️

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/skwp/dotfiles/issues/679#issuecomment-309829991>, or mute
the thread

**Comment by lfilho** [comment]
@m0n9oose care to make a small PR for us? <3

**Comment by m0n9oose** [comment]
I've tried to replace this mapping with shift version, but no luck

> The root of the problem is that Vim reads characters from the terminal, which sends ^F (ASCII code 0x06) for both Ctrl+f and Ctrl+Shift+f; Vim has no way of knowing whether you pressed the Shift key

https://vi.stackexchange.com/a/4291

**Comment by lfilho** [comment]
Oh. That's a bummer. It seems (also present in that same stack exchange answer) that NeoVim deals better with this.

What about a different combo then? Maybe with `Alt`?
