### ISSUE TITLE
update the  url of agnoster in prezto

### ISSUE THREAD

**Issue by Lumuy** [skwp/dotfiles#681]
It's like [940](https://github.com/sorin-ionescu/prezto/issues/940)

>   `./.git/modules/zsh/prezto/config:18:    url = https://gist.github.com/3712874.git`
>   `./.git/modules/zsh/prezto/modules/modules/prompt/external/agnoster/config:9:    url = https://gist.github.com/3712874.git`

**Comment by lfilho** [comment]
This was updated in Prezto so it should work fine now. Just update you prezto submodules and it should get the new changes
