### ISSUE TITLE
Why aren't the git configuration files confined to .yadr?

### ISSUE THREAD

**Issue by bridgesense** [skwp/dotfiles#684]
I'm a newbie here.  I did however successfully install yadr to the root user on my centos server.  Now I have a nifty emergency IDE I can even access from an iPad.  So I'm onboard here.

I was going to take a stab at installing this to a few individual cpanel accounts when I noticed that the git configuration files are also being symlinked to the user root dir.  What's the purpose for that?

**Comment by skwp** [comment]
You mean cat ~/.yadr/git/gitconfig? The idea is that there are additional aliases installed there. We can alternatively patch the user's gitconfig to point to ours. Maybe that's a better way

**Comment by skwp** [comment]
Happy to take a PR to fix this ..

**Comment by bridgesense** [comment]
My response is a bit late.  I'm putting this on my todo list.  It may take a couple weeks or so to get to it.

**Comment by lfilho** [comment]
@bridgesense did you get a chance to get to it? I'm not sure I understood the problem.
The installation is per user. So the git config files will be symlinked to the current users' home folder, so if you want to install for more than one user you should have to install Yadr for each user you want... No?

Feel free to elaborate more and/or close this issue if you see fit.

**Comment by bridgesense** [comment]
The repo should be confined to the YADR directory.  The problem isn't installing multiple versions of YADR.  It was more about conflict with other git repositories that may be present in the home directory.  At least for me in most cases, the current schema axes the YADR installation for production server deployment.

I thought about a few ways to handle this, but I eventually was caved in by the lack of time.   I don't have any clients who use Ruby either.  Instead I built a prototype out of bash stripping down the toolset to focus on PHP development.  I also built an Emacs initialization based on the shortcuts here.  Eventually I may do some testing with YADR, but it sounds like there aren't many who are affected by this problem anyhow.

**Comment by lfilho** [comment]
Maybe conditional configurations could help you? https://git-scm.com/docs/git-config#_includes

**Comment by lfilho** [comment]
Or you can use the good old local config file (`.git/config`) and write a bash script to auto-configure it for you cpanel users... I'm not sure how much complexity would supporting the kind of flexibility add to our code... Maybe it doesn't worth it (as it's a sporadic case...)

**Comment by bridgesense** [comment]
Exactly.  Probably not worth pursuing since I haven't seen anyone else complain about it.  Maybe this should just be closed?

**Comment by lfilho** [comment]
Your wish is my command 😄
