### ISSUE TITLE
Duplicates of Users/username/.yadr/bin:/Users/username/.yadr/bin/yadr in PATH

### ISSUE THREAD

**Issue by 7Moses** [skwp/dotfiles#690]
After a $ rake update

I see many repetitions of Users/username/.yadr/bin:/Users/username/.yadr/bin/yadr in my PATH ($ echo $PATH), 

/usr/local/var/rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/sbin:/Users/username/.rbenv/shims:/Users/username/.yadr/bin:/Users/username/.yadr/bin/yadr:/Users/username/Library/Haskell/bin:(Users/username/.yadr/bin:/Users/username/.yadr/bin/yadr)n

Used (Users/username/.yadr/bin:/Users/username/.yadr/bin/yadr)n to represent the repetitions,

I then use 

$ PATH=$(echo "$PATH" | awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}') 

… which works great, 

My PATH (after running the above) is

/usr/local/var/rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/sbin:/Users/username/.rbenv/shims:/Users/username/.yadr/bin:/Users/username/.yadr/bin/yadr:/Users/username/Library/Haskell/bin

I don't think the repetitions are a problem, just trying to get to the why it is occurring, Thanks

**Comment by lfilho** [comment]
I have just created a PR for this. Could you please review it, @7Moses ?
