### ISSUE TITLE
How to add New zsh theme

### ISSUE THREAD

**Issue by sonarforte** [skwp/dotfiles#691]
Is there an easier way to add a new zsh theme?

I wanted to modify the agnoster theme, so I copied in `yadr/zsh/prezto-themes/prompt_agnoster_setup` to `yadr/zsh/prezto-themes/prompt_myagnoster_setup`, but that wasn't enough.

I kept getting an error about plugin not found, so I then had to link that file into the zprezto modules directory, and additionally had to add in a new git repository for it (and also move the .git directory).

Is there an easier way to do this, or at least an officially documented way?

**Comment by SrEnrique** [comment]
you need make a simbolic link of your theme with `ln -s` to `~/.yadr/zsh/prezto/modules/prompt/functions` 

example 
`ln -s ~/.yadr/zsh/prezto-themes/prompt_myagnoster_setup ~/.yadr/zsh/prezto/modules/prompt/functions/prompt_myagnoster_setup`
and restart your prompt.
this works for me.

**Comment by lfilho** [comment]
@SrEnrique this way you are overwriting the original agnoster them, no? And you might loose your customization if you run the install process again...

Turns this is already documented in the repo: https://github.com/skwp/dotfiles/blob/master/doc/zsh/themes.md

So I'm closing this issue, ok? Feel free to reopen it if needed
