### ISSUE TITLE
`rake update` appending to .zshrc 

### ISSUE THREAD

**Issue by d4v3y0rk** [skwp/dotfiles#693]
running `rake update` appends to the .zshrc and cancels out and prompt settings you have there. 
https://github.com/skwp/dotfiles/blob/master/Rakefile#L328

**Comment by StefanKrauth** [comment]
There is also a pull request that would fix the append behavior: #692

However, you can make your changes in `$HOME/.zsh.after/zsh-local.zsh`. Everything ending with .zsh in the folder `$HOME/.zsh.after` is sourced after the YADR configuration.

See https://github.com/skwp/dotfiles/blob/master/zsh/zzzz_after.zsh#L4

**Comment by skwp** [comment]
the PR has already been merged thanks
