### ISSUE TITLE
Bizarre behavior when opening a directory in vim

### ISSUE THREAD

**Issue by gmaghera** [skwp/dotfiles#696]
When I open a directory in vim, NERDTree is not toggled automatically (and I'm not sure if it should, although that would be nice).  I can toggle NERDTree using the command-shift-n shortcut and it shows up just fine, but untoggling works oddly.

Say I open /usr in vim:

1.  Toggle NERDTree, and it opens showing "/usr/" as the root path.
2.  Toggle NERDTree again (trying to untoggle it).  The NERDTree display remains the same, although it seems to refresh.
3.  Toggle NERDTree for the third time.  This opens up a second NERDTree instance showing "/usr/" as the root path.
4.  Toggle NERDtree for the fourth time.  This closes the second NERDTree instance opened in step 3.

Steps 3 and 4 loop indefinitely from then on.  The original NERDTree view stays open, and the second one gets toggled on and off.

If I open vim without an argument, the toggle feature works just fine, so it seems that the issue stems from how opening of directories is handled.  I don't know vim and its autocmd feature well enough to fully understand what is going on.

Does this seem like something specific to my environment?  Can anyone else reproduce this?

**Comment by skwp** [comment]
I don't think this is a bug anymore, can't reproduce

**Comment by gmaghera** [comment]
Hmm, it's still occurring for me.  I've also noticed another behavior which seems related.

1. Launch MacVim with a directory argument, mvim /usr
2.Toggle NERDTree (command-shift-N)
3. Click into the editor pane of MacVim

Result: a second NERDTree explorer opens.

This is in no way getting into my way of working with YADR.  Just reporting it in case it is a bug.
