### ISSUE TITLE
Set default user 

### ISSUE THREAD

**Issue by PaulLafitskyi** [skwp/dotfiles#708]
How I can set default user for remove this long title username@macbookblablabla
<img width="583" alt="screen shot 2016-05-22 at 9 10 35 pm" src="https://cloud.githubusercontent.com/assets/8931303/15455593/af4b0064-2061-11e6-82da-3353b9ca6e6d.png">

**Comment by patelanuj28** [comment]
Use https://github.com/sorin-ionescu/prezto to customized your terminal.
