### ISSUE TITLE
Vim error: Error detected while processing function <SNR>211_SetAutoCmd:

### ISSUE THREAD

**Issue by andrewhl** [skwp/dotfiles#709]
Running vim or mvim causes the following error to output to console:

``` bash
Error detected while processing function <SNR>211_SetAutoCmd:
line   22:
E117: Unknown function: setinterval
```

I looked at this [github issue](https://github.com/neovim/neovim/issues/4447), and tried disabling all autocmd calls in ~/.yadr/vim/settings. I haven't tried doing that in ~/.vim/settings though.

Not really sure what's causing this. I did have a separate error earlier with tpope/surround.git. I had to uninstall it because vundle was complaining of a duplicate plugin. Not sure if that's related.

**Comment by skwp** [comment]
what mvim version are you on? I don't get this error

**Comment by andrewhl** [comment]
Sorry for the slow response. Custom Version 8.0 (110)

**Comment by andrewhl** [comment]
Would it help to completely uninstall and reinstall the dotfiles? Can you alternatively recommend a way I could debug this? I'm a bit at a loss for how to fix it.

**Comment by cdminigun** [comment]
I'm having a similar issue. I'll get back to you if I find a fix. Currently trying to reinstall .yadr, will uninstall macvim / vim and reinstall them afterwards.

**Comment by andrewhl** [comment]
@cdminigun Any chance you could document your process for uninstalling .yadr? I'm not entirely sure all the files that it writes to and how it installs or affects zsh? I'd like to uninstall and reinstall it as well but I'm nervous about breaking my environment setup.

**Comment by andrewhl** [comment]
Any word on this? @cdminigun Did you have any success?

**Comment by cdminigun** [comment]
Apologies for the late response. 

I uninstalled pretty much everything and reinstalled and ended up resolving the issue. Unfortunately it has been a while and I don't recall if I had changed anything else.

**Comment by andrewhl** [comment]
Okay, thank you. I'll try that and update this ticket with my findings.

-- 
Andrew Hlavats

On January 24, 2017 at 4:13:44 PM, Christopher Doege (notifications@github.com) wrote:

Apologies for the late response.

I uninstalled pretty much everything and reinstalled and ended up resolving the issue. Unfortunately it has been a while and I don't recall if I had changed anything else.

**Comment by cdminigun** [comment]
However, make a copy of all the changes you've made to your dot files. These won't be saved if they were in yadr specific areas.

**Comment by lfilho** [comment]
We didn't have more complaints about this and it's been a while, so I'm taking the liberty of closing this issue, ok? Feel free to reopen it if needed and please do post any relevant information for posterity sake :-) Thanks!!
