### ISSUE TITLE
Unable to extend gitconfig

### ISSUE THREAD

**Issue by fayimora** [skwp/dotfiles#710]
I created `~/.gitconfig.fayimora` and added this to it:
```
[user]
  signingkey = 990874ED
[commit]
  gpgsign = true
```

I refreshed my shell and terminal but my commits weren't automatically signed. I then ran `git config --list` and realised the settings weren't there. Any idea why? Isn't yadr "sourcing" this file?

**Comment by zitsen** [comment]
@fayimora  In `.gitconfig` you'll see:

```
[include]
  path = .gitconfig.user
```

The path name should be ` .gitconfig.user` not `.gitconfig.YOURUSER`

**Comment by fayimora** [comment]
haha my bad, silly mistake! Thanks @zitsen
