### ISSUE TITLE
Is this working under iTerm 3?

### ISSUE THREAD

**Issue by emaiax** [skwp/dotfiles#712]
I'm planning to update my iTerm to the major release on this weekend.
Does anyone already did that? Is this repo fully functional?

```
Version 3.0.0 of iTerm2

This is a major new version of iTerm2. It contains hundreds of bug fixes and
many new features. All the details are at http://iterm2.com/version3.html
```

**Comment by jby** [comment]
As far as I can tell, everything seems to work as expected

**Comment by lfilho** [comment]
@emaiax Did you try it in iTerm 3? I guess we can say yes by now and just close this issue, what do you think?

**Comment by emaiax** [comment]
Yes, it's working smoothly on iTerm 3, we can close this issue.

Thank!

—

Eduardo Maia

On Fri, 23 Sep 2016 at 06:55 Luiz Gonzaga dos Santos Filho

<
mailto:Luiz Gonzaga dos Santos Filho <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/emaiax
Did you try it in iTerm 3? I guess we can say yes by now and just close this issue, what do you think?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/skwp/dotfiles/issues/712#issuecomment-249150938
, or

**Comment by lfilho** [comment]
I can't do it by myself. Either you or @skwp must do it.

**Comment by emaiax** [comment]
@lfilho closing now, thanks, bro!
