### ISSUE TITLE
iTerm rspec runs no longer working (`zs`, `zl`, `,rl`, `,rs`)

### ISSUE THREAD

**Issue by skwp** [skwp/dotfiles#717]
Doesn't seem to be talking to iterm correctly

**Comment by skwp** [comment]
Looks like a possible syntax error with passing line numbers...

82:89: syntax error: Expected end of line but found identifier. (-2741)

**Comment by lfilho** [comment]
Almost a year on this one now, @skwp . Did the problem go away? Any known fixes?

**Comment by skwp** [comment]
This is working for me now, so shrug
