### ISSUE TITLE
alias editing is not working after upgrade

### ISSUE THREAD

**Issue by shadowing** [skwp/dotfiles#719]
HI, I've been using yadr since months ago, though not hacking into it yet. And last night I finally did an upgrade following the guide, then I tried to comment out some aliases I don't use, like `gm` for `git merge`, since this one is actually GraphicsMagick on my system, but it's not working after I `ae`; comment out; `ar`. Where should I look into to solve that? thanks.

**Comment by rjayroach** [comment]
After commenting out you would need to either start a new shell, or use `unalias gm` in the current shell

**Comment by lfilho** [comment]
What @rjayroach said is right: `ar` only sources the aliases file again, so it will only load the aliases in that file into the current session, it won't remove old ones already in it. So either you have to `unalias` them, or start a fresh session.
