### ISSUE TITLE
The root directory of YADR is changed after `rake`

### ISSUE THREAD

**Issue by zitsen** [skwp/dotfiles#723]
On a fresh install, clone the repo and do `rake` on `~/.yadr`, the `rake` stuff is going well, but re-login, it causes error:

First, in `~/.yadr`, I did `tree -L 2`:
```
.
├── addon-info.json
├── autoload
│   └── tcomment.vim
├── CHANGES.TXT
├── doc
│   └── tcomment.txt
├── etc
│   └── tpl_tcomment.txt
├── LICENSE.TXT
├── plugin
│   └── tcomment.vim
├── README
├── spec
│   └── tcomment
├── vim
│   ├── bundle
│   └── sessions
└── zsh
    └── prezto
```

Seem it's a vim script repo not yadr, the `.git/config` file shows:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/tomtom/tcomment_vim.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[submodule "zsh/prezto"]
	url = https://github.com/sorin-ionescu/prezto.git
```

it's `tcomment_vim` plugin repo, not the original cloned repo.

All these running on a new Ubuntu 16.04 (started in VirtualBox).

**Comment by bridgesense** [comment]
Just ignore me if I'm way off base here, but Ubuntu doesn't install Zsh out of the box.  That's a problem when running a .Yadr install.

**Comment by zitsen** [comment]
I've installed zsh and zsh-dev, but not help. And then, I've removed `tomtom/tcomment_vim` from
`vim/vundles/vim-improvements.vundle`, and it works well.
