### ISSUE TITLE
vimdiff suspended at startup

### ISSUE THREAD

**Issue by jby** [skwp/dotfiles#727]
Whenever I run vimdiff on two files I get this:

``` zsh
"~/src/myconfig/Mac/vim/mvim" 95L, 2553C[1]  + 57478 suspended (tty output)  vimdiff mvim ~/src/myconfig/Mac/vim/mvim
✘ ⚙ jonasb@jonasb-mp ⮀ /usr/local/Cellar/macvim/8.0-110/bin ⮀ ⭠ master ⮀ fg
[1]  + 57478 continued  vimdiff mvim ~/src/myconfig/Mac/vim/mvim
[1]  + 57478 suspended (tty output)  vimdiff mvim ~/src/myconfig/Mac/vim/mvim
```

After 'fg' twice it starts as expected.

I found https://github.com/robbyrussell/oh-my-zsh/issues/4174, which seems to be something similar, but I can't find any setting of shellcmdflags in yadr so it's not the same.
Anyone else having the same problem - and have found a solution?

**Comment by xkonni** [comment]
having the same issue. 
also, once you 'fg'ed it to run, if you run :diffupdate it's suspended again...

**Comment by gizero** [comment]
same issue here also, but haven't found the time to investigate

**Comment by podkovyrin** [comment]
Same here, but `fg` twice doesn't help.

**Comment by mengesb** [comment]
I get this behavior only with ruby files and using macvim.

**Comment by mengesb** [comment]
Also my directional keypad isn't working in ruby files... this makes editing Ruby very painful

**Comment by gizero** [comment]
Could it be related to running `vimdiff` from a shell with some Ruby specific env instead of being a matter of the file you are editing? I'm asking because I have some Ruby default env with `rvm` and friends even if I don't do Ruby related stuff often yet I see the problem with other type of files (i.e. ASCII plaintext and python files)

**Comment by podkovyrin** [comment]
I also have `rvm` installed

**Comment by mengesb** [comment]
true; i do have rvm installed... so basically i shouldn't have this then?

**Comment by mengesb** [comment]
I removed my rbenv and ruby-build using brew and I can now edit ruby files just fine without that suspending going on.

**Comment by fayimora** [comment]
I don't have either of those installed but I still get this issue. Everytime I try to diff from the fugitive status tab, vim is suspended. @jby Were you able to find a fix?

**Comment by aplatanado** [comment]
I have the same issue. I have solved it disabling [path.vim](dotfiles/blob/master/vim/settings/path.vim) but I don't know why.

**Comment by aplatanado** [comment]
I follow the issue to the last line of mi .bashrc, where the command competition is loaded. It includes a file /usr/share/bash-completion/bash_completion where I put a "return" sentence in few different lines. The issue appears with more probability when the return is more closer to the end of the file.

Something related too much time setting up the shell?

I finally put this in my .vimrc.after:

~~~
if &diff
   set shell=bash
endif
~~~

It solves the issue disabling interactive shell in diff mode.

**Comment by podkovyrin** [comment]
Disabling path.vim works for me. Thanks @aplatanado

**Comment by ClashTheBunny** [comment]
I think that the readme addresses this in this section:
https://github.com/skwp/dotfiles/#terminal-vim-troubles-with-lua
or in this section:
https://github.com/skwp/dotfiles/#macvim-troubles-with-lua

First find out which vim you use.  Uninstall the ruby installed with homebrew, install macvim, then reinstall ruby.  Don't update macvim without using the system ruby.

**Comment by lfilho** [comment]
@jby @podkovyrin @aplatanado @mengesb @gizero Could you read @ClashTheBunny's comment above and see if that's the case?
If yes, could you please close the issue or allow me to? Thanks

**Comment by mengesb** [comment]
@lfilho I'm fine; as my last comment states and alighns with @ClashTheBunny ; i removed my custom ruby env.

**Comment by aplatanado** [comment]
@lfilho I use Ubuntu so I can't apply that solution.

**Comment by lfilho** [comment]
Ok, since this repo doesn't officially support Linux, and the ruby trobleshooting is already documented, and there's some inactivity from OP, I'm closing this issue.

I have recently opened a PR which introduces Docker support which will make testing this easier, I hope. 

Cheers

**Comment by m0n9oose** [comment]
Same problem here. Just reinstalled vim with system ruby. No luck. Any thoughts?

**Comment by sitaramp** [comment]
The interactive shell is suspends the vim. I fixed the problem adding the following setting to .vimrc.after file:

" use login Shell instead of interactive shell
 if executable('zsh')
   set shell=/usr/bin/zsh\ -l
 endif

**Comment by jby** [comment]
Ran into a similar problem now on macOS 12.2.1 on Intel.
Turned out to I didn't have macvim installed this time... 😊 🤦
