### ISSUE TITLE
Remove '--all' from brewu alias

### ISSUE THREAD

**Issue by jby** [skwp/dotfiles#731]
Output when running brewu:

> Warning: We decided to not change the behaviour of `brew upgrade` so
> `brew upgrade --all` is equivalent to `brew upgrade` without any other
> arguments (so the `--all` is a no-op and can be removed).

**Comment by jby** [comment]
Being GitHub-illiterate, of course I'm unable to create a PR again :-(

**Comment by robertomg** [comment]
+1 Looks goot to me
