### ISSUE TITLE
IntelliJ Terminal - zsh: bad math expression: operand expected at `%F{135}%n%...'

### ISSUE THREAD

**Issue by Lightheaded** [skwp/dotfiles#735]
Has anyone experienced such an error in IntelliJ Idea's terminal?
![error](http://i.imgur.com/3H4Q0qt.png)

No idea how to fix it. Google says it's to do with prezto, but when I try to update just prezto, everything goes haywire. I'm running off a forked, but recently synced version of dotfiles.

**Comment by sankalpsingha** [comment]
Anyone know the solution to it till now?

**Comment by Lightheaded** [comment]
Nope. Uninstalled YADR completely and manually installed oh my zsh and other necessary stuff..

**Comment by lfilho** [comment]
@Lightheaded did this happen with regular terminals? Like iTerm? Or only with InteliJ's?
Might be an incompatibility with their terminal's bindings or how they interface stuff to zsh, idk...

It's been a semester without further developments or complaints on this, so I'm taking the liberty of closing the issue. Feel free to reopen it if anything changes.

**Comment by mojo706** [comment]
Please don't I have just had this issue. Same exact error

**Comment by lingguang1997** [comment]
Same issue here

**Comment by lightheaded** [comment]
@lfilho it was happening only with IntelliJ's terminal, nowhere else.
