### ISSUE TITLE
Ctrlp and silver searcher with folder names

### ISSUE THREAD

**Issue by fayimora** [skwp/dotfiles#736]
The ctrlp setting uses silver searcher if available. The command used is:
```sh
ag %s --files-with-matches -g "credit" --ignore "\.git$\|\.hg$\|\.svn$"
```

In the terminal, this works fine, I can search folder names too but this doesnt work in vim as it seems to only search for file names. Any idea how to get the folder name search working in vim?

**Comment by stevenbarragan** [comment]
try typing `ctrl + d` after `,t`

**Comment by fayimora** [comment]
@stevenbarragan sweet! thanks for the swift response. That worked perfectly
