### ISSUE TITLE
vim gets suspended when there is Gemfile.lock file

### ISSUE THREAD

**Issue by dongwon** [skwp/dotfiles#742]
I found a very strange symptom that vim gets suspended when there is Gemfile.lock file in the project directory.

[Reproducing steps]
bundle gem myapp
cd myapp
(Edit myapp.gemspec removing "TODO" part.)
bundle
vi lib/myapp.rb
`"lib/myapp.rb" 5L, 69C^[[2;2R[1]  + 7132 suspended (tty output)  vi lib/myapp.rb`
(When I remove Gemfile.lock file, it doesn't happen.)

[Environment]
- Ubuntu 16.04
- skwp/dotfiles from master with zsh

Is there anyone who knows this issue or can help to fix it?

**Comment by skwp** [comment]
yadr doesn't support ubuntu explicitly. This has always been an osx project. Some people tried to make it work on ubuntu but there's no official support..sorry

**Comment by lfilho** [comment]
@dongwon is this still happening? Did you find a solution or was it a one timer thing? Can we close the issue?

**Comment by mengesb** [comment]
I have this problem; and I'm on macosx 10.12.6; i just updated and I also tried re-installing macvim... 

When I move the Gemfile.lock... I get the following:

```
"spec/unit/command/generator_commands/cookbook_spec.rb" 755L, 21413C
Error detected while processing function <SNR>102_buffer_alter_paths[4]..<SNR>102_buffer_project[1]..<SNR>102_project[3]..<SNR>102_throw:
line    2:
E605: Exception not caught: bundler: not a Bundler project: /Users/<___>
Error detected while processing function <SNR>102_buffer_alter_paths[4]..<SNR>102_buffer_project[1]..<SNR>102_project:
line    3:
E171: Missing :endif
Error detected while processing function <SNR>102_buffer_alter_paths:
line    4:
E171: Missing :endif
Error detected while processing function <SNR>102_Setup:
line    2:
E171: Missing :endif
```

**Comment by mengesb** [comment]
Seems nothing I do is getting me past the following:

```
"spec/unit/command/generator_commands/cookbook_spec.rb" 755L, 21413C[1]  + 30542 suspended (tty output)  vi spec/unit/command/generator_commands/cookbook_spec.rb
user@inuyasha ~/source/github.com/mengesb/forks/chef/chef-dk (generate_LICENSE●)$ fg
[1]  + 30542 continued  vi spec/unit/command/generator_commands/cookbook_spec.rb
[1]  + 30542 suspended (tty output)  vi spec/unit/command/generator_commands/cookbook_spec.rb
```
