### ISSUE TITLE
Topical organization of folders and files

### ISSUE THREAD

**Issue by lfilho** [skwp/dotfiles#746]
@skwp what do you think of a topical approach like Holman's dotfiles for supporting different languages, plugins, and so on:

https://github.com/holman/dotfiles

Cheers

**Comment by nkgm** [comment]
Hope you don't mind my chiming in 😄 . It is an interesting approach, but I can easily this abstraction starting to leak when you bring a framework like `prezto` into the mix. On top of that, and in my specific case, I wouldn't have enough "material" per topic anyway, so I'd end up with a long list of topics with minimal content in each. Hence makes more sense to have `zsh/java-aliases.zsh` than `java/aliases.zsh`.

**Comment by lfilho** [comment]
Of course I don't mind! All brains welcome 😉 

What do you mean or how to you see this leaking happening? My idea is not to make this modules ("topics") toggleable in runtime but rather in installation time. So, for example, if I disable "ruby" it wouldn't be installed in my system and in order to install it later on I'd have to reinstall yadr...

As to your second point, I agree: we all use just a small portion of the repo features, we all have just a few topics. But that's precisely one of the pain points in the repo:
1) It causes a lot of friction to add new features or supported languages or vim plugins since all users of the repo would be getting it and getting their system bloated with stuff they don't use
2) It makes contributing back to this repo very unlikely and harder. For exempla, if I'm a Go developer, then I have to fork the repo and forked it will have to stay forever. Then eventually I might have conflicts in my fork which are impossible to cleanly rebase against the upstream (my case now). So if we had this easy way of adding and removing topics, we could easily implement an ignore or skip list for installation time ("only install ruby", "only install ruby, javascript and go", etc etc)

**Comment by nkgm** [comment]
`prezto` for example comes with multiple optional modules installed under its own root dir. I guess you could specify which modules to load in your own `topic` dirs and the installation script would take care of the rest.

 > It causes a lot of friction to add new features or supported languages or vim plugins since all users of the repo would be getting it and getting their system bloated with stuff they don't use

Good point.

> For exempla, if I'm a Go developer, then I have to fork the repo and forked it will have to stay forever.

[Dotfiles Are Meant to Be Forked](https://zachholman.com/2010/08/dotfiles-are-meant-to-be-forked/) so this is only inevitable and ultimately a good thing imho.

> So if we had this easy way of adding and removing topics, we could easily implement an ignore or skip list for installation time

Would each topic be a git submodule?

**Comment by lfilho** [comment]
Hey there.
Regarding dotfiles being meant to be forked... Maybe this came to be precisely due the difficulty of having an upstream repo easier to customize. Then indeed we can't run away from forking. Again, I'm not against that, but I think there's a huge middle ground where people fork because of only a couple of lines that differs from upstream, if that much.

And the downside being he looses the changes made to upstream while upstream also looses on any improvements that fork could have made...

As for each topic being a submodule, I didn't even think of that as of now. "Whatever works" if you ask me. Worst case scenario we could just leave the files in there (no submodules). It would be just a few extra small text files so no big deal IMHO.

**Comment by skwp** [comment]
I'm not optimistic on module support, one of the reasons I started yadr vs using something like janus  was as repo maintainer you end up maintaining a complex module system instead of a simple set of dotfiles. We already have sort of modular stuff going on under the hood with prezto and etc and I think we'll end up with a very hard to reason about system. The whole idea of yadr was to be "opinionated" meaning don't allow so much customization, just have something that works, which means the philosophy should be more fork oriented - fork and fix whatever you want. We're not really making such huge changes to yadr now so it's relatively stable. 

But I am open to other opinions if you think modular system can be done simply. I just don't want to end up holding the ball for supporting this down the line and having people frustrated that the module system isn't compatible with some newfangled thing X.

**Comment by lfilho** [comment]
I agree with you. I also don't want to increase maintainability complexity.
I'd only go for smt modular if was pretty simple and straightforward.

My main motivations were:

1. I was trying to think creatively to ways of improving the `fork > contribute back` workflow. Most of the time when we fork we never contribute back to repos like this...

2. The `before` and `after` approach (for both zsh and vim) work fine but only to add or modify configurations. If I wanted to remove (not to download or use at all) a specific vim plugin, I couldn't. I'd have to fork the repo and then, after while, due to so many conflicts, one would stop checking up (and contributing to) upstream (point 1. above)...

**Comment by skwp** [comment]
So..up to you if you want to pursue a modular system. I definitely don't have time to work on this right now but if you have smething simple that will let people opt out of certain plugins that might be nice
