### ISSUE TITLE
Rvm PATH is broken by node_modules

### ISSUE THREAD

**Issue by m0n9oose** [skwp/dotfiles#747]
Hello.

Every time i call `rvm` i see warning

```
Warning! PATH is not properly set up, '/Users/m0n9oose/.rvm/gems/ruby-2.4.0/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.4.0'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
```

Just found this strange .zsh file that changing my PATH https://github.com/skwp/dotfiles/blob/master/zsh/node_path.zsh#L1

1. Why? Why you need to add node_modules to PATH?
2. Why you add it to first place in path???
3. Is this valid path? Where it should start from? Root? My home dir?

**Comment by lfilho** [comment]
I'm not sure why we need that file (node_path), to be honest. Maybe @skwp can shine a light on the topic.
I'm a node/javascript dev and I don't see a need for it. From inside a node project, we can always do something like `$(npm bin)/myCommand` and/or use npm scripts (they also read form node_modules/bin automatically).

So if that's really the issue behind the RVM thing, I'd vote to remove this file. @skwp ?

**Comment by skwp** [comment]
I'm ok with removing this, people can set this up as they need to. As an aside I've moved to using rbenv myself and would like to remove rvm usage from this repo. Rbenv is just as good these days and doesn't have bizarre side effects such as this one
