### ISSUE TITLE
zsh: command not found: yadr

### ISSUE THREAD

**Issue by dylanpark** [skwp/dotfiles#748]
I'm trying to add my own vim plugins but yadr command is not found.
Is there a way to add plugins without using yadr plugin manager?

**Comment by katgironpe** [comment]
@dylanpark The command is not yadr. It is yav. SEE https://github.com/skwp/dotfiles/blob/master/doc/vim/manage_plugins.md

**Comment by skwp** [comment]
please see doc/vim/manage_plugins.md

you can also simply edit ~/.vim/vundles.vim and add a `Bundle whatever/whatever` line, such as ~/.yadr/vim/vundles/project.vundle
