### ISSUE TITLE
Why is the default tabsize for python file 4 spaces, instead of 2 spaces?

### ISSUE THREAD

**Issue by biniprc** [skwp/dotfiles#759]
I found the fact that default tabsize for python file is 4 spaces.

Anyone knows why this is happening and how to set it to 2 spaces?

<img width="197" alt="2017-06-06 5 30 11" src="https://cloud.githubusercontent.com/assets/9452521/26820455/d50c1ef8-4add-11e7-8151-1db4373a7133.png">

**Comment by lfilho** [comment]
AFAIK we don't change that for specific languages. Maybe you have an `.editorconfig` file in your project's root dir?
Or maybe a python-specific plugin is setting that?

**Comment by skwp** [comment]
We're not doing anything special for python please override as needed

**Comment by giorni** [comment]
And I think the default is related to [PEP8](https://www.python.org/dev/peps/pep-0008/)
