### ISSUE TITLE
custom vim color schemes in .vim/colors

### ISSUE THREAD

**Issue by shved** [skwp/dotfiles#761]
Hi there!

Please provide a convenient way to add custom vim colorschemes in .vim/colors. Forking the whole project just to add a color scheme is not quiet good option. Thanks! Great dotfiles.

**Comment by lfilho** [comment]
You can add custom colors via the `~/.vimrc.before` and `~/.vimrc.after` files...

**Comment by lfilho** [comment]
@shved can i close this?

**Comment by lfilho** [comment]
Closing by inactivity.
