### ISSUE TITLE
Installation on Ubuntu 17.04 causes failure in GUI

### ISSUE THREAD

**Issue by yonilerner** [skwp/dotfiles#764]
Steps to reproduce:
- Install git
- Install rake
- Install zsh
- Install yadr
- Reboot

After restarting, any attempt to login via the Ubuntu GUI will cause a black screen and force `lightdm` to restart. This loop will continue indefinitely. The only solution that worked for me was to change my shell back to `bash`. This indicates to me that there is something in the `zsh` configs that yadr is setting up causing X to crash (Ctrl + Alt + F1 to login with a terminal has no issues).

Another potentially relevant point is that Im using an nVidia graphics card with the nVidia drivers installed from their website, and my `.Xauthority` was updated by whatever automated system their drivers setup.

I dont know enough about yadr or Linux to debug this issue myself, but Im very happy to provide any debugging info from my system if people could point me in the right direction. Im moving away from macOS, and I desperately want yadr with zsh to work properly, as its been a staple of my development environment for 4+ years.

**Comment by yonilerner** [comment]
Another relevant piece of information: After logging in, I can use `zsh` with yadr just fine. It only seems to be a problem if its my login shell

**Comment by lfilho** [comment]
The main contributors don't use linux so we also can't easily test it. We have a Docker image and in there it works fine.

So I'm afraid you need more help of other linux users...
