### ISSUE TITLE
Small nit. Extra set of quotes.

### ISSUE THREAD

**Issue by jon-choi** [skwp/dotfiles#767]
Thanks for sharing your super clean vimrc. Inspired me to do some spring cleaning of my own.

https://github.com/skwp/dotfiles/blob/c112c85efc978a15f04d18813c2297cb4a141ba4/vimrc#L103

**Comment by lfilho** [comment]
Glad you liked it. Kudos to mainly to @skwp .
Could you open a PR, please?
