### ISSUE TITLE
Duplicate vim bundle breaks javascript indenting

### ISSUE THREAD

**Issue by AdrianArtiles** [skwp/dotfiles#775]
Just recently did a `rake update` and found smart/auto indenting in VIM for javascript files broken.

After some investigation I believe I narrowed it down to a re-emergence of the issue of `mxw/vim-jsx` being added as a duplicate in this file [here](https://github.com/skwp/dotfiles/blob/master/vim/vundles/languages.vundle#L8).

In the commit where `mxw/vim-jsx` was added, [this comment](https://github.com/skwp/dotfiles/commit/6ab2d71522bb43f3c40fae14f3781667c81a25f8#commitcomment-20061583) highlighted the issue that I am now experiencing again.

In short `mxw/vim-jsx` is already included in `sheerun/vim-polyglot` and the duplicate plugin is causing issues. When I remove `mxw/vim-jsx` everything works as expected.

That plugin was then removed in [this commit](https://github.com/skwp/dotfiles/commit/6594c2a5930891b6341a394ddc1ea3248807274a) by @lfilho resolving the issue.

However, it seemed this issue was re-introduced in [this commit](https://github.com/skwp/dotfiles/commit/fb4bec51f05ef47e56fca2d21acd20b4f38c6010) when `mxw/vim-jsx` was re-added by @skwp .

I'm guessing it was re-added by accident, not realizing the issue it previously caused.

Let me know if I'm missing anything. Otherwise, I think the fix is just simply re-removing `mxw/vim-jsx`!

**Comment by forgetaboutme** [comment]
I removed the ```mxw/vim-jsx``` and am still having issue with indentation. Whenever I type ```{}```, there is no newline + no indentation.

**Comment by deepcut** [comment]
@AdrianArtiles found this b/c I had the same issue!

**Comment by chrischen** [comment]
I can confirm that removing vim-jsx fixed the issue for me too, and doing so there is no newline + indent when doing `if (...) {` + Enter.

**Comment by lfilho** [comment]
Hi folks, I'm using my own fork of this repo, which has drifted a lot so I can't test and debug this.

If someone one finds a permanent solution and others help test it and confirm the solution here, I'd gladly help review and merge that CR.
