### ISSUE TITLE
Setting profile

### ISSUE THREAD

**Issue by refaelos** [skwp/dotfiles#778]
Hey,

What's the best way to set profile with yadr?
I mean, all the exports (PATH, JAVA_HOME ...).

Thanks!

**Comment by YurkinPark** [comment]
for $PATH, i think you can inject your bin path here https://github.com/sorin-ionescu/prezto/blob/4f19700919c8ebbaf75755fc0d03716d13183f49/runcoms/zprofile#L44 but not sure, because zsh fill path variable earlier as well

**Comment by lfilho** [comment]
You can also add anything in `$HOME/.zsh.before/*.zsh` it it will get sourced. This is a good way cause this won't get you git workdir dirty.

There's also https://github.com/skwp/dotfiles/blob/3166caa39714bd3c9535a0307b86efc589dfc6c7/zsh/0_path.zsh but this will leave your workdir dirty if edited...
