### ISSUE TITLE
no need for Seil from Sierra

### ISSUE THREAD

**Issue by casouri** [skwp/dotfiles#779]
From macOS Sierra, you can set Caps to Esc from System Preference.

**Comment by lfilho** [comment]
Can you sent Esc to Caps Lock at the same time?

**Comment by casouri** [comment]
No you can't set Esc to Caps

**Comment by lfilho** [comment]
So we still need Seil, right? ;-) The goal is to swap the two of them so we can have both features avaiable.

Closing this for now

**Comment by casouri** [comment]
You are right.
