### ISSUE TITLE
Feature Addition: Pomodoro Timer

### ISSUE THREAD

**Issue by jeffthefate** [skwp/dotfiles#780]
Good idea? Rediculous?

Can't be dependent on the internet (why would it need to be?)

**Comment by lfilho** [comment]
I believe this goes agains the goal of the repo... If we open up for this, than soon enough we'll be adding many flavors of different tools for different purposes... You can imagine how that goes...

I'd say this kind of personal and productivity tools should live in forks or in the before/after files where you can customize the repo.

Does it make sense? Feel free to close this issue if you agree.

**Comment by lfilho** [comment]
Closing due to lack of correspondence from OP.
