### ISSUE TITLE
Customise Powerline

### ISSUE THREAD

**Issue by nWidart** [skwp/dotfiles#783]
Hello,

Is there a way for us to customise the powerline prompt theme?
For instance I would like to set the `dir_shorten_len` or `dir_limit_depth` options ([source](http://powerline.readthedocs.io/en/master/configuration/segments/shell.html)).

Thanks!

**Comment by lfilho** [comment]
Try this link from the README: https://github.com/skwp/dotfiles/blob/master/doc/zsh/themes.md

**Comment by nWidart** [comment]
Thanks, but this doesn't answer the question.
As you can see your link only talks about adding a new prompt theme.
