### ISSUE TITLE
Tab completion stopped working after update

### ISSUE THREAD

**Issue by josesa** [skwp/dotfiles#790]
Yesterday I tried to update my Yadr instalation by executing `rake update` but it somehow didn't work as expected. (unfortunately I don't have the output anymore).

The issue is I lost all tab completion, file and commands/aliases.

The command `complete` returns empty
I also cleared `rm ~/.zcompdump*` files but without any luck.

How can this be debugged?

**Comment by andrewash** [comment]
This is broken for me too.
I think it broke after running ```brew update && brew upgrade```

Now whenever I start a terminal session I see this output to the terminal window:
```
Last login: Thu May  3 16:27:57 on ttys000
add-zsh-hook () {
	emulate -L zsh
	local -a hooktypes
...
```
