### ISSUE TITLE
Ruby Version Warnings

### ISSUE THREAD

**Issue by preist** [skwp/dotfiles#794]
When I run vim with RVM Rubies, I get these warnings:

![2018-04-25 10 44 39](https://user-images.githubusercontent.com/14940633/39232409-e42cc25c-4875-11e8-9f36-30fcfeab86b5.gif)

What could be causing these and how to fix them?

**Comment by preist** [comment]
I use `rvm` to manage Ruby versions. The errors disappear if I set the system Ruby as main.

```
$ rvm use system --default
```

I would prefer to set one of the `rvm` rubies as my default.

**Comment by faucct** [comment]
Plugin [vim-iterm-rspec](https://github.com/skwp/vim-iterm-rspec) is the problem. It uses `ruby` vim feature – the one vim was compiled with (system), while a list of installed gems comes from rvm env. I have got rid of these warnings by commenting out the plugin in `~/.vim/vundles/vundle`.

**Comment by preist** [comment]
Thanks @faucct, I was able to comment it out in my `~/.vim/vundles/ruby.vundle`

```vim
Bundle "ecomba/vim-ruby-refactoring"
Bundle "tpope/vim-rails.git"
Bundle "tpope/vim-rake.git"
Bundle "tpope/vim-rvm.git"
Bundle "vim-ruby/vim-ruby.git"
Bundle "keith/rspec.vim"
" Bundle "skwp/vim-iterm-rspec"
Bundle "skwp/vim-spec-finder"
Bundle "ck3g/vim-change-hash-syntax"
Bundle "tpope/vim-bundler"
```
