### ISSUE TITLE
Aaaaalway occur this issue when installing

### ISSUE THREAD

**Issue by TorvaldsDB** [skwp/dotfiles#798]
![image](https://user-images.githubusercontent.com/12232166/41693793-93dedae2-7539-11e8-897e-a8371269076d.png)

**Comment by lfilho** [comment]
Does that `PlugClean` in there mean you're using Plug? This repo doesn't have Plug, but Vundle.
If that's the case, please check you have migrated from Vundle to Plug correctly. I'm closing this for now with the above assumption. Feel free to open it again if you can provide more details and hopefully repro steps
