### ISSUE TITLE
Really Slow Ctrl-P with Syntax Highlighting

### ISSUE THREAD

**Issue by chrischen** [skwp/dotfiles#800]
I'm using MacVim and YADR and after opening two files in split mode, Ctrl-P typing becomes super slow and window resizing seems to be running at < 5 FPS. I also tested in iTerm running Vim and Ctrl-P typing becomes sluggish as well.

Steps to reproduce.
1) Open two files split vertically of at least a few hundred lines
2) Use Ctrl-P and type something
3) Turn syntax highlighting off
4) Ctrl-P becomes super responsive when typing

**Comment by lfilho** [comment]
Has anyone been able to reproduce this? I don't use MacVim nor CtrlP anymore. @chrischen did it get better for you by any chance with newer versions of CtrlP?

**Comment by chrischen** [comment]
I turned on caching, and switch to "ag".

```
 let g:ctrlp_user_command = 'ag %s --files-with-matches -i --nocolor --nogroup --hidden
        \ --ignore ".*"
        \ --ignore ".git"
        \ --ignore "*.png"
        \ --ignore "*.jpg"
        \ --ignore "*.psd"
        \ --ignore "*.gif"
        \ --ignore "*.tif"
        \ --ignore "*.tmp"
        \ --ignore ".svn"
        \ --ignore ".hg"
        \ --ignore ".vagrant"
        \ --ignore "*.DS_Store"
        \ --ignore "node_modules"
        \ --ignore "**/*.pyc"
        \ -g ""'
  let g:ctrlp_use_caching = 1
```
