### ISSUE TITLE
Ruby issue on Mojave

### ISSUE THREAD

**Issue by nWidart** [skwp/dotfiles#802]
Hello,

I've upgraded to Mojave and since then I'm getting the following error when using vim:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:17:in `require': incompatible library version - /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/stringio.bundle (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1230:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1230:in `<module:Gem>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:116:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

I found that maybe it could be due to the gems being installed as sudo. I've used `rbenv` to install the latest version of ruby (2.5). 
However, when running the vim command I still get the same issue using version 2.3.

Is there something to do so that vim uses the latest version?

I've also checked my `$PATH` which contains the rbenv bin path.

Thanks!

**Comment by nWidart** [comment]
Not sure if best solution, but adding the following to the vimrc file works:


```
let $RUBYHOME=$HOME."/.rbenv/versions/2.5.1"
set rubydll=$HOME/.rbenv/versions/2.5.1/lib/libruby.2.5.1.dylib
```

**Comment by pswaminathan** [comment]
This isn't a tenable solution. I'm not working with Ruby, so no rbenv for me. Is there a way to address this without needing to install rbenv? What gem is being installed that is causing this? Can I uninstall?

**Comment by jasonwbarnett** [comment]
> ```
> /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:17:in `require': incompatible library version - /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/stringio.bundle (LoadError)
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:17:in `<top (required)>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1230:in `require'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1230:in `<module:Gem>'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:116:in `<top (required)>'
> 	from <internal:gem_prelude>:4:in `require'
> 	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
> ```


@pswaminathan #794 fixed the problem for me.

**Comment by pswaminathan** [comment]
@jasonwbarnett yes, I edited my comment accordingly.

**Comment by bzx** [comment]
> Edit: found a workaround in #794 commenting out a bundle.
> This isn't a tenable solution. I'm not working with Ruby, so no rbenv for me. Is there a way to address this without needing to install rbenv? What gem is being installed that is causing this? Can I uninstall?

For me this is not a sensible solution either. Any other ideas?

**Comment by danilol** [comment]
> Not sure if best solution, but adding the following to the vimrc file works:
> 
> ```
> let $RUBYHOME=$HOME."/.rbenv/versions/2.5.1"
> set rubydll=$HOME/.rbenv/versions/2.5.1/lib/libruby.2.5.1.dylib
> ```

This solved my issue. Thanks!
