### ISSUE TITLE
lazy loading

### ISSUE THREAD

**Issue by nrolland** [skwp/dotfiles#807]
To use `nvm` I added a `nvm.zsh` which loads the installed nvm configuration

```
$ cat nvm.zshslow                                                                                       
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

This take a long time at launch time.  What is the recommended way for lazy loading such completions/initialization ? (or is it easier to simply pack those less used features in a script to run when used..)

**Comment by PetroccoCo** [comment]
I haven't tried anything yet but some poking around led me to https://github.com/benvan/sandboxd and this post: https://frederic-hemberger.de/articles/speed-up-initial-zsh-startup-with-lazy-loading/
I'll probably check them out after the holidays

**Comment by lfilho** [comment]
Where you guys able to speed it up?

**Comment by PetroccoCo** [comment]
I never got around to checking out the proposed speedups.

**Comment by lfilho** [comment]
Ok. Closing this since it's not specific to this repo but actually a zsh thing. Feel free to post findings here for future folks visiting the thread.
