### ISSUE TITLE
Prezto Completion

### ISSUE THREAD

**Issue by cdenneen** [skwp/dotfiles#819]
What’s the best way to add a completion to prezto? 
Best I’ve found is adding files to the prezto/modules/completion/external/src directory which I know is bad practice.

**Comment by lfilho** [comment]
Not sure as I never added an extra one, but did you try play with the `after` feature? https://github.com/skwp/dotfiles/blob/master/zsh/zzzz_after.zsh or if you have your own fork, then maybe adding to the `prezto-override` folder and configuring it there?
