### ISSUE TITLE
It didn't work on Manjaro-KDE

### ISSUE THREAD

**Issue by Joarell** [skwp/dotfiles#828]
_**$ sh -c "`curl -fsSL https://raw.githubusercontent.com/skwp/dotfiles/master/install.sh`"
Installing YADR for the first time
Cloning into '/home/jev/.yadr'...
remote: Enumerating objects: 213, done.
remote: Counting objects: 100% (213/213), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 213 (delta 2), reused 157 (delta 2), pack-reused 0
Receiving objects: 100% (213/213), 708.00 KiB | 1.58 MiB/s, done.
Resolving deltas: 100% (2/2), done.
sh: line 7: rake: command not found**_

I have tried to install YADR on Manjaro-KDE however it didn't work. The installation just stops as you can see above.
Would you please give me some help?

**Comment by pablobender** [comment]
@Joarell, you need Ruby/Rake installed on your system. Some tasks are done using `rake` (make utility for ruby).

**Comment by Joarell** [comment]
Oh god!
It run perfectly! 
Hi @pablobender!
Nice to e-meet you!

Thank you! Thank you so much for your kind help!
Success!

**Comment by Joarell** [comment]
Ahahahahahahha...
Só agora eu olhei no seu perifl para notar que você é brasileiro!
Poxa vida!
Que felicidade meu caro!
Estou utilizando o Linux a poucos meses e o seu pacote para o Vim é sensacional!
Desejo muito sucesso a você! De verdade mesmo!

**Comment by pablobender** [comment]
nice to meet you too @Joarell 
In fact I do not use this repository as it is. I have my own fork from it so I receive the GitHub notifications. :-p and the vim's plugins set/configuration from here is really amazing.

**Comment by lfilho** [comment]
Glad it was sorted out. (Também sou brasileiro) hehe
