### ISSUE TITLE
TMUX conf issue

### ISSUE THREAD

**Issue by rockwarrior** [skwp/dotfiles#836]
I just installed yadr on my Macbook Pro running macOS Catalina 10.15.4 and tried to launch tmux with `tmux new -t work`. I'm seeing the following error. `.tmux.conf:30: unknown key: C- if-shell`. I'm running tmux version 3.0a_1.

**Comment by duccuong2808** [comment]
I found solution in https://github.com/christoomey/vim-tmux-navigator/issues/243
Please change like:
```
# line 30
bind -n 'C-\' if-shell "$is_vim" "send-keys C-\\" "select-pane -l"                                                                                          
```

**Comment by rockwarrior** [comment]
Sorry @duccuong2808, I'm not exactly sure how this applies since we're not trying to bind a key... How would we modify `if-shell "[ -f ~/.tmux.conf.user ]" 'source ~/.tmux.conf.user'`

**Comment by rockwarrior** [comment]
Thanks @duccuong2808 that worked!
