### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Gregliest** [skwp/dotfiles#837]
It appears that the blog link on this line is no longer active. 
https://github.com/skwp/dotfiles/blob/b0a060c1d039709352a4c184a843b46c078ea7d6/git/gitconfig#L19

I think [this](http://philjackson.github.io/2013/04/07/handy-git-tips-to-stop-you-getting-fired.html) might be the updated link.

**Comment by nandalopes** [comment]
Maybe this is the new link:

<http://philjackson.github.io/2013/04/07/handy-git-tips-to-stop-you-getting-fired.html>

Or this:

<http://www.gitalias.com/>

**Comment by vovinacci** [comment]
According to [Web Archive](https://web.archive.org/web/20190419165317/http://blog.apiaxle.com/post/handy-git-tips-to-stop-you-getting-fired/l) [this](http://philjackson.github.io/2013/04/07/handy-git-tips-to-stop-you-getting-fired.html), indeed is the correct link.
