### ISSUE TITLE
How to customize zsh prompt

### ISSUE THREAD

**Issue by Teg79** [skwp/dotfiles#838]
The docs don't explain how to change the prompt and how to make a custom one.
It would be very useful to know all the functions we can use in the prompt, the colors, the formatting and where to write the customization to make it effective.

**Comment by lfilho** [comment]
Did you check https://github.com/skwp/dotfiles/blob/master/doc/zsh/themes.md ?

Other than that I believe it would be auto of scope for this repo as it would be about teaching zsh internals... If you find a nice link explaining those things in zsh's documentation for example, we could at least link it on the file above, for sure.

**Comment by Teg79** [comment]
Thanks, I was unable to find it. I managed to customize one setting the RPROMPT env variable to put the current date time on the right

`export RPROMPT=“%D %T”`
