### ISSUE TITLE
Homebrew halts installation on a fresh MacOS

### ISSUE THREAD

**Issue by jagjotsinghparry** [skwp/dotfiles#844]
Hey,

When installing YADR on a fresh installation I noticed that Homebrew fails because the installation method has changed. I am attaching the screenshot for the same. 

I can open a PR for the required change. 😃 

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/4722099/93115039-fdd22d00-f6d8-11ea-918a-e9e9c4fcf3b2.png">

**Comment by lfilho** [comment]
Sure, a PR is most welcome
