### ISSUE TITLE
Vim suspends in some times

### ISSUE THREAD

**Issue by Zaryob** [skwp/dotfiles#845]
I'm using yadr in Mac and Debian at the same time. But sometimes especially in hidden files (dotfiles) it crashes and suspends immediately. and all command prompt goes down until opening a new terminal

```
~ ❯❯❯   vim .yadr/git/gitconfig
.yadr/git/gitconfig" 134L, 4252C[1]  + 25862 suspended (tty output)  vi .yadr/git/gitconfig
```

When I open same file's link in my home ~/.gitignore it dont gives me any error.

And also I use vim as commit editor. It also crashes on editing a commit message. 

I use it in both OS'es Mac and Debian

**Comment by Zaryob** [comment]
![image](https://user-images.githubusercontent.com/22801690/94342565-d421db80-ffdf-11ea-899e-93bab13e855a.png)
When I use CTRL-D or CMD-D it runs as well but when I enter `:wq` or `:q` it closes terminal as well

**Comment by Zaryob** [comment]
I tried also in tmux. Same issue.

**Comment by Zaryob** [comment]
[Uploading myVim.log…]()

**Comment by Zaryob** [comment]
```
 3522 autocommand if g:colors_name != "solarized" | silent! aunmenu Solarized | else | call SolarizedMenu() | endif
 3523 
 3524 autocommand if g:colors_name != "solarized" | silent! aunmenu Solarized | else | call SolarizedMenu() | endif
 3525 
 3526 Error detected while processing ColorScheme Autocommands for "*": 
```

**Comment by vovinacci** [comment]
@Zaryob That's quite old and nasty bug.  As per [this comment](https://github.com/skwp/dotfiles/issues/727#issuecomment-381285224), you may want to add to `~/.vimrc.after`
```
" use login shell instead of interactive shell
if executable('zsh')
  set shell=/usr/bin/zsh\ -l
endif
```
Worked for me.
