### ISSUE TITLE
vim-coc install blocked by our vim plugin manager (Vundle)?

### ISSUE THREAD

**Issue by christophermlne** [skwp/dotfiles#846]
What would be the level of interest here to get vim-coc working as part of the default yadr installation?

vim-coc has become pretty much a hard requirement in some environments due to the industry adoption of Typescript.

I think we will need to switch to a different plugin manager than vundle as vim-coc does not work with vundle and the author of vim-coc told me he would never add support for vundle. I was able to get vim-coc installed by hacking around the limitations of vundle.

the supported plugin managers are here, for interest
https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim

**Comment by christophermlne** [comment]
for additional context, i'm at a crossroads with respect to yadr.
my options are:
- try to get vundle replaced in yadr officially
- maintain a fork of yadr
- start a new dotfiles repo
- switch to VS Code :-1:

**Comment by lfilho** [comment]
Hey @christophermlne 

I'm not @skwp but I occasionally help maintain this repo. I believe skwp will not like this idea and would definetely expect a PR for this as, IIRC, he mainly works with ruby (not js/ts). Are you able to provide one?

If not, you might be interested in my repo -- it's a fork of this one after many years of fighting upstream :-) I use Plug as well some more javascript oriented plugins. https://github.com/lfilho/dotfiles vim-plug is on master but coc not yet, it's on a branch called `[coc2](https://github.com/lfilho/dotfiles/tree/coc2)` you might wanna give that one a try. If you're willing to contribute and chisel the edges out we can merge it back to master.

Cheers

**Comment by christophermlne** [comment]
@lfilho thanks for the reply.

i will definitely check out your repo.

my current line of thinking on this is i will attempt to migrate the parts of yadr i can't live without to a nix-based set of dotfiles (using nix home-manager to manage them), so unless that goes very wrong i won't be submitting an upstream PR.

**Comment by skwp** [comment]
Hey guys, I don't have a strong opinion here as I definitely don't have time to maintain this repo. Those who do @lfilho are welcome to make big decisions without me :)

I'm also doing a lot more javascript these days so I'm happy to have more js oriented fixes.
