### ISSUE TITLE
add rebase = false for git pull in .gitconfig pls

### ISSUE THREAD

**Issue by astkaasa** [skwp/dotfiles#854]
or rebase = true / ff only

git version 2.29.2 has a prompt of warning if there's no such config

**Comment by nandalopes** [comment]
hi, you can add this on your own `.gitconfig.user` file:

```
[pull]
  rebase = false # or rebase = true, or ff = only
```

**Comment by lfilho** [comment]
That also seems like a personal preference in the end, so i'm reluctant in adding one for the whole repo, unless there some solid reasoning behind it which i might not be aware of.

PRs are welcome :)
