### ISSUE TITLE
Neocomplete is no longer compatible with Vim versions 8.2.1066+

### ISSUE THREAD

**Issue by jmalvinchin** [skwp/dotfiles#877]
The neocomplete included in the bundle is no longer compatible. Perhaps the new plugin [deoplete](https://github.com/Shougo/deoplete.nvim) can be used instead?

**Comment by thecadams** [comment]
+1 for this, seems like this repo isn't maintained anymore though..

It'd be great to find a solution here - perhaps someone out there is maintaining a fork of this repo?

**Comment by lfilho** [comment]
Yea, im maintaining my own. Feel free to have a look around. It focus on neovim and some different plugins

**Comment by kathgironpe** [comment]
@thecadams I have not found a solution other than switching to neovim and maintaining my own dotfiles. COC & neovim works. I still like YADR a lot so I maintain a fork without neocomplete. Downgrading to lower versions for Vim does not make sense too.

**Comment by lfilho** [comment]
Sorry to hear that folks. I've been with my own fork of this repo with neovim and coc as well. 

Happy to merge a fix here if anyone finds one

**Comment by kathgironpe** [comment]
@lfilho I do not have PR for this because I am still testing my MacVim setup. I also maintain a separate neovim setup. Both work. 

For those who use Vim 8.2+, I found completor.vim. It is the only option that worked. COC did not work. 

https://github.com/maralla/completor.vim

I started making notes on installation with Yadr here:

https://gist.github.com/kathgironpe/63bef270589bf7451eba924a3bb733a1

**Comment by kathgironpe** [comment]
I think the library to be used for Code Completion may depend for your needs. 

YCM works for me. 

I found faster versions like https://github.com/prabirshrestha/vim-lsp.
COC.vim may work for a lot, but I honestly will never use it even for `neovim` setup. 

For the YADR fork I maintain, YCM is my option. 
I am currently testing https://github.com/prabirshrestha/vim-lsp. 

Someone should create a PR. 
A lot of us will have very opinionated setups based on our needs. 
But it's still good to fix the `neocomplete.vim` issues and replace it with something similar. I vote for https://github.com/prabirshrestha/vim-lsp.

**Comment by kathgironpe** [comment]
Just an update:

Over the past few months, I have `CoC.nvim` for both NeoVim and Vim8, and I decided to completely switch to using `vim-lsp`. So far, it works better and has less configuration.

You will need https://github.com/mattn/vim-lsp-settings

CoC gave me errors on some days so I no longer use it for any environment/OS.
