### ISSUE TITLE
Unable to install yadr due to issue w/ Chezmoi and nproc?

### ISSUE THREAD

**Issue by rajuashok** [skwp/dotfiles#882]
I'm trying to install YADR on an M2 MacBook Air. When running the install script I get the following error:

```
chezmoi: template: private_dot_config/mr/groups.d/00-personal.tmpl:1:14: executing "private_dot_config/mr/groups.d/00-personal.tmpl" at <output "nproc">: error calling output: nproc: exec: "nproc": executable file not found in $PATH
```

I thought it may have still installed fine, but when opening a new terminal I'm not seeing any of the aliases or yadr niceties available. 

Is there an issue with apple silicon?

**Comment by rajuashok** [comment]
So I deleted everything and ran the following:

```sh -c "`curl -fsSL https://raw.githubusercontent.com/skwp/dotfiles/master/install.sh`"```

That seemed to work.

Running this is what caused issues and did not install anything:
```sh -c "`curl -fsSL https://github.com/nandalopes/dotfiles/raw/main/root/bin/yadr/install.sh`"```

**Comment by pdehlke** [comment]
Very belatetdly and for the record: the nandalopes fork of this repo explicitly does not support MacOS, and Nanda is pretty hostile to suggestions for portability. If you want the `chezmoi` management framework that Nanda wrote and MacOS support, you can check out my fork of his repo: [pdehlke/dotfiles](https://github.com/pdehlke/dotfiles/tree/main). The relevant fix for this specific issue is [here](https://github.com/pdehlke/dotfiles/commit/db912c78d2e7622f4c5634c836e4937c327bdb6f)
