### ISSUE TITLE
Compatibility issue with YADR and NVM. NVM always installs from source

### ISSUE THREAD

**Issue by matheustavaresdev** [skwp/dotfiles#885]
Due to this alias https://github.com/skwp/dotfiles/blob/master/zsh/zsh-aliases.zsh#L7 it makes NVM always build and install from source instead of binaries. 

Not really sure how to fix it and if this should be fixed at all, but after commenting that line it worked for me. Posting mainly for awareness if someone is experiencing the same issue.

https://github.com/nvm-sh/nvm/issues/3094#issuecomment-1517839451

**Comment by ljharb** [comment]
This is an issue with zsh global aliases overall; they’ll break any portable sourced script, which nvm is.

**Comment by matheustavaresdev** [comment]
This seems to only happen on a few versions of `nvm`. Confirmed version to occur: `v0.39.3`. Should be fixed when next version comes out. Fixed at https://github.com/nvm-sh/nvm/pull/3012

**Comment by ljharb** [comment]
That’s because of the specific conflict with “L” - *any* global zsh aliases risk conflict in the future.
