### ISSUE TITLE
Issue with .exists? for ruby 3.2

### ISSUE THREAD

**Issue by nogeek** [skwp/dotfiles#891]
Ruby 3.2 no longer supports .exists?

Please add me as a contributor and I will submit a pull request to fix this. thanks!

**Comment by redsfyre** [comment]
I was able to run yadr on Fedora 39 by installing ruby 3.1 with rvm. 
I wanted to write here in case anyone gets an error and can't figure out how to fix it

**Comment by jravetch** [comment]
Having the same issue, how can I help?
